= Cosmoglotta
:author: Marcos Cruz (programandala.net)
:revdate: 2021-04-29
:toc:
:toc-title: Contenete/Contents

// This file is part of project
// _Cosmoglotta_
//
// by Marcos Cruz (programandala.net)
// http://ne.alinome.net
//
// This file is in Asciidoctor format
// (http//asciidoctor.org)
//
// Last modified: 20210429T2101+0200.

== Interlingue

=== Pri ti projecte

Scope:: Converter li contenetes de _Cosmoglotta_ (solmen li volumes
1927/1950), li central jurnale de Interlingue, in libres digital in
EPUB e altri formates.

Autores:: Dave MacLeod, 2018/2019; Marcos Cruz, 2019/2021.

Web-locs::
1. textification: http://cosmoglotta.pbworks.com[cosmoglotta.pbworks.com]
2. librification digital: http://ne.alinome.net[ne.alinome.net]

NOTE: In 2020-12-04 li depositoria de Git esset convertet a un
http://fossil.ne.alinome.net/cosmoglotta[depositoria de Fossil],
conservante http://github.com/ne-alinome/cosmoglotta[GitHub] quam un
copie.

== English

=== Abouth this project

Goal:: Convert the contents of _Cosmoglotta_ (only the volumes
1927/1950), the main magazine of the Interlingue/Occidental language,
into ebooks in EPUB and other formats.

Authors:: Dave MacLeod, 2018/2019; Marcos Cruz, 2019/2021.

Websites::
1. text conversion: http://cosmoglotta.pbworks.com[cosmoglotta.pbworks.com]
2. e-book creation: http://ne.alinome.net[ne.alinome.net]

NOTE: On 2020-12-04 the Git repository was converted to a
http://fossil.ne.alinome.net/cosmoglotta[Fossil repository], keeping
http://github.com/ne-alinome/cosmoglotta[GitHub] as a mirror.
