= Cosmoglotta
:author: Marcos Cruz (programandala.net)
:revdate: 2023-04-06
:toc:
:toc-title: Contenete/Contents

// This file is part of project
// _Cosmoglotta_
//
// by Marcos Cruz (programandala.net)
// http://ne.alinome.net
//
// This file is in Asciidoctor format
// (http//asciidoctor.org)
//
// Last modified: 20230406T1109+0200.

== Interlingue

=== Pri ti projecte

Scope:: Converter li contenetes de _Cosmoglotta_ (solmen li volumes
1927/1950), li central jurnale de Interlingue, in libres digital in
EPUB e altri formates.

Autores:: Dave MacLeod, 2018/2019; Marcos Cruz, 2019/2023.

Web-locs::
1. textification: http://cosmoglotta.pbworks.com[cosmoglotta.pbworks.com]
2. librification digital: http://ne.alinome.net[ne.alinome.net]

=== Historie del depositoria

- 2019-05-04: Li depositoria de Git esset publicat
  https://github.com/ne-alinome/cosmoglotta[in GitHub].
- 2020-12-04: Li depositoria de Git esset convertet a
  https://fossil-scm.org[Fossil], conservante GitHub quam un copie.
- 2023-04-06: Li depositoria esset convertet a
  https://mercurial-scm.org[Mercurial], possibilisante un melior
  interaction con GitHub.

== English

=== Abouth this project

Goal:: Convert the contents of _Cosmoglotta_ (only the volumes
1927/1950), the main magazine of the Interlingue/Occidental language,
into ebooks in EPUB and other formats.

Authors:: Dave MacLeod, 2018/2019; Marcos Cruz, 2019/2023.

Websites::
1. text conversion: http://cosmoglotta.pbworks.com[cosmoglotta.pbworks.com]
2. e-book creation: http://ne.alinome.net[ne.alinome.net]

=== History of the repository

- 2019-05-04: The Git repository was published
  https://github.com/ne-alinome/cosmoglotta[in GitHub].
- 2020-12-04: The Git repository was converted to
  https://fossil-scm.org[Fossil], keeping GitHub as a mirror.
- 2023-04-06: The repository was converted to
  https://mercurial-scm.org[Mercurial], enabling a better interaction
  with GitHub.
