// This file is part of project
// _Cosmoglotta_
//
// by Marcos Cruz (programandala.net)
// http://ne.alinome.net
//
// This file is in Asciidoctor format
// (http//asciidoctor.org)
//
// Last modified 202008141639

// Pri ti libre {{{1
== Pri ti libre

Titul:: Cosmoglotta.

Descrition:: Oficial organe del lingue international Interlingue
(Occidental), quel es publicat desde 1927.

Textification e actualisation del ortografie:: Dave MacLeod, 2018-2019.
Obtenibil in http://cosmoglotta.pbworks.com[cosmoglotta.pbworks.com].

Conversion a Asciidoctor, revision, corection e edition quam libre digital::
Marcos Cruz, 2019-2020{dot} Obtenibil in
http://ne.alinome.net[ne.alinome.net] in formates EPUB, PDF e altris.

Principal changes in ti edition::
- Corection de omni trovat erras.
- Amelioration del leibilitá, precipue de tabelles e listes, por omni
  formates.
- Creation de intern ligamentes.

Libre digital fat solmen per líber programas::
http://asciidoctor.org[Asciidoctor],
https://github.com/asciidoctor/asciidoctor-epub3[Asciidoctor EPUB3],
https://github.com/asciidoctor/asciidoctor-pdf[Asciidoctor PDF],
http://docbook.sourceforge.net/release/xsl/current/epub/README[dbtoepub],
http://debian.org[Debian],
http://git-scm.com/[Git],
https://www.gnu.org/software/make/[GNU make],
http://neovim.io[Neovim],
http://pandoc.org[Pandoc],
http://http://jonas.nitro.dk/tig[Tig],
http://vim.org[Vim],
http://xmlsoft.org/XSLT/[xsltproc]…

// Version de ti edition:: {revnumber}.

Contributiones:: Corectiones e suggestiones por sequent versiones es
benevenit che http://ne.alinome.net[ne.alinome.net].

NOTE: Li nómine de Interlingue esset «Occidental» til 1949.

