= Cosmoglotta (mancant numerós in li document principal)

// This file is part of project
// _Cosmoglotta_
//
// by Marcos Cruz (programandala.net)
// http://ne.alinome.net
//
// This file is in Asciidoctor format
// (http//asciidoctor.org)
//
// Last modified 201908110201

// Cosmoglotta A 051-052 (aug-sep 1928) {{{1
== Cosmoglotta A 051-052 (aug-sep 1928)

// XXX REMARK -- Ti numeró en es li viena muséo, solmen li covriment:
//
// http://anno.onb.ac.at/cgi-content/anno-plus?aid=e0g&datum=1928

COSMOGLOTTA

Organ mensual del Association International Cosmoglotta

Consacrat al developation, propaganda e aplication del Lingue
International Auxiliari Occidental

Redaction e Administration: COSMOGLOTTA, Mauer bei Wien, Austria.
Abonnament annual: 7 ö. S = 1 doll. = 5,2 sv. fr = 4,2 RM = 33 čsl. K

Annu VII – August-Septembre 1928 – Nr. 51, 52 (8,9)

Numeró special dedicat al membres del Ido-Congress Zürich, 2 til 5
august.

// Contene {{{2
=== Contene

- Psicologie interlinguistic, de Ric. Berger, pg. 117.
- Idés directiv e principies de Ido, de Ric. Berger, pg. 118.
- Duplic consonantes, de Ric. Berger, pg. 19.
- Tro mult suffixes!, de Ric. Berger, pg. 120.
- Suffix -ion, de Ric. Berger, pg. 121.
- Obliviates, de Ric. Berger, pg. 123.
- Apelle por solidaritá, de Ric. Berger, pg. 123.
- Qui es li autor de Occidental?, de Ric. Berger, pg. 124.
- Novial, de E. Pigal, pg. 125.
- Novam e Novial, de A. Z. Ramstedt, pg. 127.
- Un Progress?, de Albert Haldin, pg. 134.
- Índiscret question a Senior Jespersen, de Ric Berger, pg. 125.
- Cronica, de E. Pigal, pg. 126.
- Criterie de L.I., de E. W., pg. 138.
- Quelc opiniones de sviss Idistes, pg. 139.
- Textu comparativ, de Karl Janotta, pg. 140.
- Noticies, de E. P., pg. 140.

// Psicologie interlinguistic {{{2
=== Psicologie interlinguistic

// XXX TODO -- Confirmar ca li paroles de Dudouy es dividet in du
// paragrafes:

Ancor nu, yo memora un remarcabil articul publicat de sr Abat Dudouy
in «La Langue auxiliare», julio 1914, quel exposit un fact psicologic
tre curios: «Si vu discusse», scrit sr Dudouy, «con un Esperantist, vu
ne have pena far le conceder li necessitá de mult reformas; strax il
agnosce que Esperanto vell esser plu bon sin li acusativ obligatori,
sin li plural del adjective, sin li inventet correlatives, … to es su
opinion privat e li ver, nam ti-ci ne es falsat de considerationes
sentimental …

Ma si vu questiona le pro quo il ne adhere a Ido, quel ha supresset
omni ti desfacilitás, strax li Esperantist indignat responde: a Ido?
nequande! … e poy … il comensa contestar li utilitá del reformas self,
queles il quelc minutes antey trovat necessi! …».

Evidentmen to es un contradition astonant, enorm, ma quant homan! Tant
homan que hodie noi constata li sam fact che li Idistes córam
Occidental.

// XXX NOTE -- Ci esset li marca original de págine -118-

Noi conosse eminent Idistes, queles ante un annu demandat in Ido just
ti reformas, queles Occidental ha realisat (precipue in grammatica e
derivation). Ante 6 mensus, córam li progresses de Occidental, ti sam Idistes
scrit nos que li bonitá de ti formes ne es pruvat e nu, pos nor
adhesion a Occidental, ili trova que omni ti formes «es un regress»!

Yo vell posser citar Vos li casu de un excellent coidealist, quel
acrimen vole absolutmen e sistematicmen vider grav defectes in Occidental.
Por ex., il critica li -a por li feminin pro que un parol quam «matra»
vell chocar li Italianes! Noi responde que Occidental ne have matra ma matre,
pro que ti parol es ja feminin per se self e ne besona un finale
feminin. — «Ergo», responde nor amico, «Occidental have exceptiones, paroles
feminin ne fini per -a, quáncam ti -a indica ti sexu. Esque on posse
subtener un lingue tam desfacil e ínregulari?».

«Car senior», yo responde, «ante departer in guerre, ples solmen
remarcar que Vu vide li pallie in li ocul del altris» — «Senior, yo ne
permisse que …» — «Yes, ples remarcar que in Ido tam regulari Vu di:
«matro» e ne «matrino», quo constitue exactmen li sam exceptiones quam
in Occidental …»

It ne existe plu grand surdes quam tis, qui ne vole audir.

_Ric. Berger_

// Idés directiv e principies de Ido {{{2
=== Idés directiv e principies de Ido

Córam li rapid progresses del conception occidentalistic li secretario
del Ido-Akademio sentit li beson redemonstrar li excellentie del
principies de Ido. (Vide «Ido», april 1928). Noi do va anc rediscusser
les.

// XXX NOTE -- li marca original de págine -119- esset pos listun 2:

1) «Internationalitá del radicas (del radicas, ne del tot paroles
format)». Pri li principie inter parenteses noi responde: tant plu
regretabil. Un ver lingue international deve haver ne solmen radicas,
ma anc derivates international, e si Ido eliminat ti ultimes per un
mal derivation, to es un grand defect ne a exposir quam un principie!

2) «Autonomie pri derivation e composition». — Ples remarcar que
Occidental have anc ti avantage tam bon quam Ido. Ma li derivates de
Occidental es identic a natural paroles internationalmen conosset,
contra que li Ido-derivates, tro autonom, es artificial formes sovente
íncomprensibil.

3) «Unisensitá in li paroles e renversabilitá in li derivation». — Si
yes, noi questiona pro quo in Ido vocabules quam «nivo, pluvo» ne
seque li regules general del derivation; pro quo li resultate del
action «pluvar» ne es «pluvuro», quam de «disertar» es «diserturo»? Li
response es tre simplic: li regules de Couturat es tam contrari al
customes del popules, que on ne audaciat applicar les partú. Do on
creat exceptiones.

4) «Fonetical ortografie» (!) — Quam exemple noi va citar li son k
scrit in Ido per 3 manieres: qua, exemplo, kun; li son s anc per 3
manieres: eceso, ex; li son z per 2 manieres: exemplo (gs), rozo; anc
li i consonante yes, filio, etc.

Ples remarcar que noi ne blama ti alfabet, in contrari, it esset un
grand progress sur li alfabet esperantic; ma to quo noi ne admisse, es
li pretension que ti alfabet es fonetic. On save tre bon que to es
fals. Un alfabet fonetical in li L.I. ne es possibil pro que it vell
deformar horribilmen li grafisme international e far li lingue
ínreconossibil.

5) e 6) Ci sr de Beaufront exposi principies tam elastic que ili posse
pruvar omnicos quo on desira. Ili vell posser justificar omni L.I.
bon o mal, secun qualmen on aplica les.

_Ric. Berger_

// Duplic consonantes {{{2
=== Duplic consonantes

Nor amicos Idistes es obsedet de un horribil fantom: li duplic
consonantes. Por ex. li redactor de «Ido» publica que: «… un L.I. con
duplic lítteres es li fonte de multissim erras e ne vell esser
aprensibil ante plur-annual studias»!

Vice repetir vacui paroles, it vell esser mult plu bon regardar un poc
li practica quel sol decide. Li Occidentalistes afirma e pruva que li
max facil lingue ne es li max simplic teoreticmen, ma li max conform
al customes del lingues national. Ergo, pro que li lingues natural
have ancor duplic consonantes, un L.I. ne deve obligar li adeptes a
altri acustomation. Ti adeptes va scrir plu instinctivmen fortissim,
acceptar, errore, etc, quam fortisim, aceptar, erore.

// XXX NOTE -- li marca original de págine -120- esset in li sequent
// paragraf:

To es tam ver que li presc unic errores queles on incontra in lettres
idistic, proveni del obliviantie de ti reduction. Por ex. in un
circulare de un redactor idistic qui usa Ido desde 10 annus, noi lee
«me assertas»! Un poet idist, in li lettre self u il combatte li
duplic consonantes, scrit «me essus», e ples remarcar que li verb
esser es li max usat. Li president de un
Ido-gruppe svissian scri ancor nos: «acceptez». Esque ti exemples
inter multis ne es un decisiv pruva que Occidental seque li regules
del psicologie?

It es tre amusant constatar que li unic consonantes posse esser anc li
«fonte de mult errores». Sur li covriment del ultim numeró de
«Ido-Francia» noi lee deci vezes li parol «dolaro». Probabilmen nor
confratre ne ja conosse li exception votat del Ido Akademio: li rect
Ido-parol es «dollar». Ti qui vide exceptiones solmen in Occidental, ne have
témpore por vider les in Ido!

Al Idistes qui considera li duplic consonantes quam impediment por li
publica, noi da li consilie releer li opinion de Mgn. Foucault,
episcop de St. Dié, un venerat poet idistic. In li numeró festiv de
«Idisto Katolika», de 1926, Mgn. Foucault declara que il ne aproba
completmen Ido pro «li mutilation, quel sin beson es inflictet a pluri
radicas latinid p. ex. a terre, ferre quande etc, queles Ido mutilat
in «tero, fero, kande».

_Ric. Berger_

// Tro mult sufixes! {{{2
=== Tro mult sufixes!

Quelc Idistes reprocha a Occidental su tro grand númere de sufixes (in
Ido 47, in Occidental 60). Ma ples remarcar que E. de Wahl ne inventet ni un
sol, ma extraet les omni del lingues vivent con lor just sense; ergo,
omni ti afixes es ja conosset de homes civilisat qui ne besona
aprender les. On dit anc que Occidental have quelc vezes du sufixes por li
sam idé; ma in ti casu un del du sufixes ne plu es vivent o es usat
solmen in li lingues scientific. Ido anc have li sam casu con «-oida»,
quel sembla far duplic usation apu «-atra», e quel támen es usat in li
lingue scientific. Noi do ne comprende pro quo li Idistes reprocha nos
li sufixe -ment apu -age. Si Ido ne adoptet -ment, in revancha, it
esset obligat adopter quam nov radicas pluri paroles logicmen derivat
in Occidental mersí a ti suffix. Por ex. li «Lexique-manuel» de Guignon
contene li sequent duplic radicas in Ido: abutar, abutmento; basa,
basamento; detachar, detachmento; suplear, suplemento; experiencar,
experimento; fondar, fundo (!), fundamento; sentar, sentimento;
kompletar, komplemento; ligar, ligamento; mediko, medikamento; ornar,
ornamento; sakra, sakramento; segar, segmento.

// XXX NOTE -- Ci esset li marca original de págine -121-

Ti exemple sufice por pruvar que ti «ínutil» suffix -ment permisse
sparniar un dozen de radicas. Mani sufixes idistic ne have tam grand
avantage!

Un altri suffix -atu esset anc criticat pro que «-eso» es suficent. Si
yes, tande noi questiona pro quo Ido have «konkubinato» apu
«konkubino» (quam nov radica) si «konkubineso» vell esser sufficent? E
pro quo malgré li analogie, Ido have támen «pontifikeso», «kalifeso»,
ma «majorato»?

_Ric. Berger_

// Sufix -ion {{{2
=== Sufix -ion

Pro que null sufix es plu international quam -ion, on posse esser
astonat que it ne existe in Ido, etsi venit mult propositiones por
introducter it. Ja in 1909 (vide «Progreso», II, 22) Dr Boubier, prof.
in li universitate de Genève, exposit su necessitá talmen: «Yo esset
sovente frappat del internationalitá del suffix «ation» in li paroles
scientic. Studiante plu profundmen li question, yo esset convictet que
li scientistes absolutmen va besonar e voler conservar ti sufix,
quande ili va far li divers lexicos scientic. In general on posse dir
que li sufix «ation» es usat con li signification: action expresset
del radica verbal.» Ti excellent proposition de un scientist ne esset
discusset del Ido-Akademio pro que it vell har obligat li change del
esperantic base, … li sam argument quam por mult altri ameliorationes
necessi.

Ma li formes international es tro potent por esser tacet long témpore
e comprensibilmen li suffix -ion ne tardat reaparir. In «Mondo» esset
publicat recentmen mult propositiones, ma quam monstra tre bon sr
Gerald A. Moore in «Mondo» marte 1927, «… pro li Esperantan base de
Ido ti vocabules vell esser totalmen ínregulari e sin logical
relation, … si on desira adopter li vocabules in -ion sembla que es
necessi haver verbes in -ar (educar: education), in -ir (definir :
definition), in -er (expresser : expression; adopter : adoption)».

// XXX NOTE -- li marca original de págine -122- esset in li sequent
// paragraf:

Ci es li node del question: Si Ido vole adopter li sufix max
international e max usat, it es obligat acceptar li solution de Occidental e
abandonar li base Esperantic. On comprende to que li ductores de Ido
sercha omni sortes de objectiones, queles monstra solmen que li suffix
-ion es por Ido quam li uves por li fox: tro verdi! In «Ido», febr.
1928, sr de Beaufront
explica que si -ion ne es admisset, to es pro que -ion significa tande
action (p. ex. abolition), tande insecte (papilion), e tande person
(histrion = comediant)! Ma contra ti argument null sufix vell posser
resister! Pro quo Ido adoptet li suffix «-il» malgré «gentila,
humila», li sufix -in malgré «mashino, origino, magazino» etc, li
suffx «-ul» malgré «kanulo, primulo» etc, li sufix -ur malgré
«inauguro, kurbaturo», li sufix -ier malgré «frontiero» etc? Si li
objection de sr de B. vale quelc-cos, it es ínpossibil prender
quelcunc sufix in li lingues national pro que ne existe un sol quel ne
have pluri senses si on vole bon serchar. Factmen malgré «papiliono e
histriono», li sufix have un sense general corespondent al suffix -o e
-ado de Ido por li action, quam sr Boubier ha bon monstrat it. Un
altri argument de sr de B. es vermen astonant: Autores pruvat que -ion
ne es bon, per … ne admisser it inter li multi sufixes de lor
sistemas! Noi responde que, in contrari, -ion deve esser tre bon pro
que li max mult autores de L.I. adoptet it. Pro quo serchar
exceptiones vice li majorité?

Finalmen sr de B. afirma que -ion da paroles tro long e que «noi deve
evitar formes repugnant pro ínutil longore e desbell ponderositá». Si
yes, yo questiona pro quo, ante quelc mensus (in «Idisto Katolika»,
dec. 1927), sr de B. denove publicat un articul de Couturat con li
noticie sequent: «Pro li form international: evolution, involution,
tam frequent usat del scientist, e pro li necessi derivates:
evolution-ism, evolution-ist etc, li Ido-Akademio substituet li
paroles «evoluciono, involuciono» a «evoluc, involuc», chocant li
scientie e minu bon comprensibil. It anc viceat «subvenco» per
«subvenciono» («subvencionar») quam plu clar e strax comprensibil quam
«subvenco» («subvencar»). Anc li paroles «subvencionanto,
subvencionario» es plu bon quam «subvencanto, subvencario».

Esque sr de B. ne vide que li vis-punctu de Couturat justifica paroles
quam redaction, diferentie etc vice: redakto, difero (pro redaktional,
diferential). E támen ti paroles es minu long quam «subvencionario»
quel il aproba!

_Ric. Berger_

// Citate {{{2
=== Citate

// XXX FIXED -- Li titul "Citate" esset mettet in ti edition.

[quote, H. Ford]
____

Si noi possede hodie comod medies de transporte, — to veni de to, que
li popul esset pret expenser pecunie anc por íncomod medies de
transporte, e talmen lassat maturar li sistema.

____

// XXX NOTE -- Ci esset li marca original de págine -123-

// Obliviates {{{2
=== Obliviates

«Li opinion de sr Guignon e de me es, que «dub» es un heredage de
Esperanto quel escapat in li revision del talones, secun queles esset
composit nor unesim vocabularium sub li controla del comission
permanent». Talmen scri sr de Beaufront, li secretario del academie
idistic in «Ido», may 1927. E tande il proposi li just radica: dubit,
sin dir que il prende it de … Occidental.

Pro que sr de Beaufront comensa li revision del Ido-vocabularium, noi
humilmen fa remarcar le que «dub» ne es li sol obliviat e que mult
altri radicas anc escapat; p. ex. «sen» e «se», queles es minu
international quam sin e si (Si Esperanto ne posset adopter les, it es
pro li accusative de «si», pronómine personal, ma tal impediment ne
existe in Ido); «nek» es minu international quam ni e «ni», pronómine,
minu quam noi, etc.

Quam altri heredages de Esperanto noi vell posser anc citar li
suffixes: -ulo, -ema, -inda, -ilo, -uyo, -ega, queles es inventet,
contra que li suffixes -o, -aci, -bil, -or, -uor, -essim es ja
conosset de milliones de homes.

On vide per ti exemples que existe in Ido mult formes plu important
quam «dub» queles besona esser «revizata»!

_Ric. Berger_

// Apelle por solidaritá {{{2
=== Apelle por solidaritá

«L’ Informisto», organ del belgian Idistes, publica un apelle al
Idistes pro que li edition del «Gramatiko detaloza» «ha inmerset por
pluri annus in dolores e desfacil situation un ex nor max brav
combattentes».

Desde long témpore noi conosse quant devoet es sr Meier de
Esch-Alzette (Luxemburg) por li afere del L.I. e, etsi noi ne adplu
es in su camp, noi compate le pro su doloros situation.

Ma noi questiona: quant ínutil sacrificies e penas on vell har evitat
si, in 1907, li Delegation vell har proposit al mundlinguistes un ver
lingue international, simil a Neutral reformed, vice un Esperanto
ínsuficentmen ameliorat, un compromisse, quel ne contentat ni li
Esperantistes, ni li progressistes. Talmen on perdit 20 precios annus,
li témpore e li pecunie de mult devoet idealistes. E hodie, ti errore
noi paya!

// XXX NOTE -- Ci esset li marca original de págine -124-

Noi questiona: pro quo li important Memorandum, quel sr de Wahl misset
al Delegation in Oct. 1907 e quel indicat li sol just via a secuer,
restat in li archives del Delegation sin esser studiat? It contenet
támen li ver principies del futur international lingue e vell har
evitat un ínfelici experientie.

_Ric. Berger_

// Qui es li autor de Occidental? {{{2
=== Qui es li autor de Occidental?

Edgar de Wahl, nu professor de matematica e fisica in Reval (Estonia),
es un erudit, qui conosse 12 lingues de Europa, e festat su 60-ésim
anniversarie li 11 august 1927. Unesimmen adept de Volapük, il adheret
a Esperanto pos su aparition in 1887 e indicat a Zamenhof quelc erras
in su lingue, p. ex. li temporal correlatives «tian, kian, ĉian»,
queles colidet con li acusativ del demonstratives «tia, kia, ĉia»; e
Zamenhof strax mutat «tian, …» in «tiam, kiam, ĉiam».

Pos Zamenhof e Grabowski (ambi morit) de Wahl es li 3-esim autor de un
librette in Esperanto. Ergo, on posse dir que de Wahl es li max ancian
Esperantist vivent.

In 1894 Zamenhof proposit a su adeptes important reformas simil a Ido,
reformas repulset per 157 voces contra 107. Remarcabil es, que sr de
Beaufront e sr Ahlberg votat contra omni change. Tande E. de Wahl
abandonat Esperanto, tro artificial por il, e il comensat laborar vers
li direction naturalistic, sempre corespondent con altri
mundlinguistes, precipue con Lott, de qui li final sistema
«Mundolingue» debi mult ameliorationes a de Wahl.

In 1906 E. de Wahl publicat un project «Auli» (Auxiliari Lingue
International), quel ja havet li aspect de Occidental ma ne su regules
de derivation, quel esset decovrit solmen plu tard e poc a poc. Quande
in 1907 li Delegation apertet concurs inter li projectes de L.I. por
adoption del max bon, E. W. mult auxiliat li ingeniero Rosenberger a
ameliorar Idiom Neutral quel esset presentat sub li nómine de «Neutral
reformed» al Delegation, quel finalmen selectet Esperanto, «pro su
grand difusion». E. W. self misset al Comité del Delegation un
memorandum quel indicat li ver principies del L.I.: naturalitá e
regularitá, supression del formes inventet.

// XXX NOTE -- li marca original de págine -125- esset in li sequent
// paragraf:

Pos li publication de Ido, E. de Wahl strax indicat li defectes de
principies e de detallies. On corectet solmen un poc
de ili secun su criticas, precipue li prefixe mal- esset viceat per
des-.

On vide de que li 3 cardinal lingues international: Esperanto, Idiom
Neutral e Ido debi important ameliorationes a sr de Wahl de qui li
principies sempre plu triumfat.

Finalmen, in 1922, vidente que li question del L.I. devenit important
til atraer li atention del Liga de Nationes, E. de Wahl decidet
presentar li resultate de su 30 annus de cosmoglottic investigation in
un sistema complet sub li nómine de Occidental. Sin capitale, sin
dictionarium, sin grammatica, li propagation esset restrictet in
comensa che quelc circules de Idistes progressistic, per li micri
jurnal «Kosmoglott». Mersí a su sol qualitás intrinsic, li lingue
ganiat adherentes e in 1927 un gruppe de ingenieros viennes,
organisatores del unesim congress de Ido in 1921, qui per li organ
«Cosmoglotta» comensat un sistematic propagande e desarmat poc a poc
li prejudicies del progressistic mundlinguistes.

_Ric. Berger_

// Novial {{{2
=== Novial

Li majorité de nor letores idistic ja es informat pri li aparition del
project Novial de prof. Jespersen. Noi ancor ne ha publicat un
recension pro preca de sr J. atender til publication de su detalliat
libre redactet in lingue angles. Etsi in li momente ti libre ancor ne
atinget nos, noi támen inserte in li present numeró li relatent
articules, anc pro que interim sr J. ja comensat propaganda por su
sistema per altri publicationes. Quande noi va har recivet li ovre
angles con su motivationes noi ancor un vez va presentar in li págines
de nor jurnal un response, ex li plum de senior de Wahl.

In su public epistul in «Mondo» nr 209, sr J. confesset que il ha
aprendet ne solmen de Zamenhof e Couturat, ma anc de de Wahl.

// XXX NOTE -- li marca original de págine -126- esset in li sequent
// paragraf:

Max grand li influentie de Occidental es remarcabil in li derivation verbal
de Novial. Ci nu anc li tema verbal fini per un vocale, a quel es
adjuntet p. ex. li solmen consonantic finales participial: -nt e -t.
Sr J. ha compilat a un multicolori mosaic li derivation de Occidental con su
«fonetical» ortografie. On remarca misstilies e anacronismes, quam
«sivilisatione (civilisation), sosialisatione (socialisation), vivasi
nationalisatione (vivaci nationalisation), sent diferentiationes (cent
diferentiationes),
i. e. paroles con aspect de cap de «Janus bifrons», regardant in avan
al futur e in detra al passat.

Sr J. aconosse li avantage del renunciation pri li fix sense del
finales grammatical. Fortunosimen il totalmen ha abandonat li rigoros
mediat verbisation denominal e li quasi-matematic schema del
«renversebleso», quel adver esset laudat de Dr. Couturat quam un del
max splendid qualitás de Ido.

Novial adopte li suffixes de Occidental: -ari, -aci (-asi), -isa(r)
-ifica(r); ma it conserva de Esp-Ido: -ilo, -eso, -aro. Novial repulse
li Esp-Ido-suffix -ega (decapitat grec mega) e prende -isi, i.e.
-issim con amputat m. -arie have li sam arbitrari restrictet sense
quam Ido -ario.

Li consonantes p e c in li latin numerales sept- e oct- ha assimilat
se in li romanic lingues a -t. Conform a ti process Occidental have: set e
ot. In Novial noi trova: sep e ok, ex Esp-Ido e contra li leges
fisiologic pri li mutation de sones. Li Novial paroles: patron (= de
patre), homan (= de fémina), homesen laboros (= labores de homes) es
simil al famos images vexativ e charades de Esperanto: maskulino (=
mascata), foresto (= absentie), sesono (= sixesim) etc.

Prof. Jespersen critica li semblant exceptiones de Occidental, quo
támen ne posse impedir le usar por li participie de presentie: -ent
pos -i-, -u-, apu -nt pos -a-, -e-. Ma li regul de Occidental pri li
pronunciation de c (ante e, i, y: ts, in altri casus k) secun prof. J.
es tro desfacil e il prefere deformar li customat scrition de un imens
númere de frequent paroles international: sentimetre (cm), sosial
(social), konserte (concert) etc.

In Novial simil quam in Occidental on accentua li vocal ante li ultim
consonante. Ma li síllabes de flexion es ínaccentuat. Do omni hom in
li parlada, ante distribuer li accentu, deve pensar esque li ultim
síllabe es un flexionale o ne. Noi ci ne vole disputar esque ti ci
regul es condamnand in un L.I., ma noi solmen demanda que on mey
mesurar per li sam metre li desfacilitá anc del regules de Novial ante
proscrir li sistema de Occidental. Noi opine que por li ordinari hom
li duesim regul de accentuation in Novial es plu desfacil quam li
simplic tal de Occidental pri li pronunciation del c. Li facilitá del altri
regules de Novial, apartmen del derivation, chascun self va constatar,
comparante les con tis de Occidental. In céteri punctus noi torna li
attention de nor letores al scientific tractate de nor secretario del
Comité Explorativ Mag. A. Z. Ramstedt, filolog comparativ, in li
present caderne.

// XXX NOTE -- Ci esset li marca original de págine -127-

Si sr J. ante publication vell har experimentat su sistema durant
quelc annus (e por autor de un mundlingue to vell esser li minimal
deventie) il self vell trovar, quel del principies del du divers
directiones (schematisme secun Esperanto e naturalisme regularisat
secun Occidental) es conciliabil, sin detriment al homogenitá e
practicabilitá del idioma. Li practic aplication monstra que un verbal
sistema secun ti de Occidental sta e cade con li etimologic
ortografie.

Etsi forsan li nov ovre de prof. Jespersen va mem augmentar li cáos nu
reyent in li camp de Ido, yo tamen espera que li libre del conosset
anglist va evocar por nor comun idé alcun interesse in li neutral
publica quel til nu ancor crede que li mundlingue es o Esperanto o
Angles.

Noi do deve expresser a sr Jespersen (qui in li sequent annu va
atinger su 70 annus) nor mersías, pro que il ha interprendet li labore
scrir li protocolle de su idés captet desde li exflorescentie de Ido.

_E. Pigal_

// Novam e Novial --  Du nov projectes de lingue international {{{2
=== Novam e Novial --  Du nov projectes de lingue international

// XXX NOTE -- li marca original de págine -128- esset in li sequent
// paragraf:

In li ultim mensus ha esset publicat presc ye li sam témpore du nov
projectes: Novam — de Sr G. Touflet, Paris, e Novial — de prof. O.
Jespersen, Copenhagen. Proque ambi essentialmen vole esser
ameliorationes de Ido, quel ya in su órdine esset un reformat
Esperanto, ambi monstra un interessant similitá. Novam ha esset
presentat per un jurnal «Novam – Gazeto Internasiona», de quel du
numerós ha aparit (marte e april 1928, contenent letura e grammatica).
Novial ha esset introductet per articules in «Mondo» e altri idistic
jurnales, in li presse de Scandinavia, e per un libre in li dani
lingue, «Et Verdenssprog» (Pios Boghandel, Copenhagen, 74 pag., 1 D.
Kr.). Noi saluta ti du nov projectes quam signes de to, que li
interesse por nor nobil idé sempre vive che divers nationes. Ma ye li
sam vez noi ne posse celar nor regreta pri to, que ili ne contribue al
solution del problema, ma al confusion del present situation. Ti
desilusion relate specialmen a Novial, proque it ya ha esset anunciat
ja de long in ante de su autor, mem córam li grand publica, e it ha
esset expectat con grandissim interesse de omni interessates, queles
ha esperat que it va adportar nos alquicos nov. Pro ti publicitá noi
es fortiat tractar li projectes ci. Ambi sembla ancor esser
in stadie de elaboration, ma to quo ja es publicat, da nos sufficent
materiale e motive por declarar nor desinteresse.

Etsi on senti in ambi projectes li influentie del idés del
naturalisme, ambi es evident productes del mecanic-schematic scole,
quel ha productet tam grand númere de lingues. Li structura de tal
lingues depende ya essentialmen del desir del autor: «sic volo, sic
jubeo». Ma it es clar, que si ne existe altri criterium quam li
decides e desires de quelc individues, on posse crear un imens númere
de lingues, nam apen du homes have li sam pensas. Li unitá, quel noi
omnes desira, resta ínobtenibil per tal metodes.

Ambi autores appari quam reformatores del ortografie. lli ne es
content con li actual scrition del international paroles, specialmen
li duplic usation de c. Sr Touflet prescri c e s, Sr Jespersen k e s.
Novam scri: consernant, ma Novial: konsernant (Occidental: concernent),
Novam: sivilizo, serta, Fransa, Novial: siviliso, serti, Fransi, seso
(Occidental: civilisation, cert, Frances, cessa). Noi vide in Novam tal
scritiones quam cener (German: kennen), ercener (G erkennen), cezo
(Occidental: caseo), cem (Occidental: quande), ci (Occidental: qui), ma cc es
exceptionalmen pronunciat x: acceptar, accelerar, succesar, u Novial
have regularimen: tu aksepta, tu akselera, tu suksesa.

Pri li vanitá de tal reformas in li scrition de international paroles,
antequam simil reformas es fat in li grand cultural lingues, ha esset
scrit pluri articules in nor jurnales. On posse far ortografic
reformas in vivent national lingues, nam tá on ya have li existent
pronunciation quam normativ, ma in un artificial LI, quel ancor ne es
parlat, un tal base de referentie ne existe. Lu normativ va esser li
desir de un individue pri li pronunciation e scrition de international
paroles, un tro debil base. On posse constatar un internationalitá de
scrition, ma absolut ne un tal de pronunciation.

// XXX NOTE -- li marca original de págine -129- esset in li sequent
// paragraf:

Comprensibilmen li intention del autores ha, esset far li scrition del
paroles plu facil. Ma secun nor opinion ili ha fat li lingue plu
desfacil. Li reformatores va esser fortiat prescrir un nov ortografie
por milles de international paroles, sciential terminologie, nómines;
e li usatores va esser fortiat obliviar li acustomat scrition e
aprender li nov. Advere prof. Jespersen permisse traditional scrition
de geografic nómines, un eclatant pruva que li question have anc su
practic látere, ne solmen teoretic. Ma li cose have anc un estetic
látere. It es conosset que li non-romanic scrition per k e s de
romanic
paroles, es repugnant por li romanic popules e por li angleses («the
German Kultur»), ma li usation de c totmen ne es to al altri popules,
quo monstra li predilection de germanes e scandinaves usar c vice k in
nómines: Carl, Conrad, Campe, Cassel, etc. Anc Novial es essentialmen
romanic in su vocabularium, e li scrition per k e s pro to da it un
«barbaric» aspect. — Ambi ne audacia usar ni duplic consonantes, ni li
líttere y quam signe por vocal, prof. Jespersen mem ne li líttere z.

Concernent li grammatica, ambi autores ha concentrat special attention
al pronómines. It existe un abundantie de inventet formes. P. ex. li
personal e possessiv pronómines: Novam: pers. pron., subj.: me, tu,
vu, lu, le, lo, ni, vi, li, uli, eli, oli; obj. (facultativ): mi, te,
vo, lur, ler, lor, vir, etc.; poss. pron.: mea, tua, vua, lua, lea,
etc. etc. Novial: me, vu, le, lo, la, lum, nus, vus, les, los, las,
lumes (abreviat lus); obj. (facultativ): mem, vum, lem, lom, lam, lum,
nusem, vusem, etc. poss. pron.: men (existe un casu genitiv per -n),
vun, len, lon, lan, lumen, nusen, vusen, lesen, losen, lasen, lumesen
(abreviat lusen).

Li intention de prof. Jespersen ha esset obtener ne solmen absolut
regularitá che li pronómines ma anc li sam flection quam che li
substantives. To sembla nos un exageration del importantie del
regularitá. In realitá it es pret paroles, queles un aprendent e
parlant deve memorar e usar, ne radicas plus afixes, e it es un cose
conosset (vide p. ex. E. Tegnér: Språkets makt över tanken), que
schematisme ne auxilia li aprension. Li homan memorie besona firm
punctus por adherer, e just pro lor ínperfectitás e ínregularitás li
natural lingues da nos plu secur adhesion por li memorie.

// XXX NOTE -- li marca original de págine -130- esset in li sequent
// paragraf:

Li nov projectes difere concernent li conjugation: Novam tende a un
sintetic: amer, aman, amed, amar, amud, hav amat, had amat; Novial a
un analitic: tu ama, ama, did ama (o ámad), sal ama, vud ama, ha ama,
had ama. Curios es li passiv de Novial: bli ama, blid ama, etc. Si
internationalitá e comun europan lingual usu have alquant
signification, on certmen deve preferer li conjugation de Occidental. Null
europan lingue constructe perfect e passiv per auxiliares plus tema
verbal, quam in Novial es proposit, ma omnis usa perfect participe,
anc li scandinavic lingues, queles di: bli älskad, e ne bli älska. Li
infinitive de Occidental «amár» es certmen mult plu bon quam «tu ama». Li
accentuation sur li tematic vocale auxilia li memorie e conservation
de it, -r quam inf.-signe es panromanic
e conosset anc in german e slavic verbes: G telephonieren, Sv
telefonera, R telefonirovat’. It es a observar, que anc Novial ha
introductet tematic vocales che li verbes, e ne tri quam che Occidental, ma
quar: tu ama, tu voli, tu rupte, tu distribu. Qualmen it va esser
possibil memorar ti quar ínaccentuat vocales, queles bentost va
devenir ínclar e confuser se, es un problema. In Novial on posse
formar sintetic conditionales per -ud: povud, musud (mus = Occidental: deve),
esud, ma solmen che li auxiliares, nam qualmen acter che li verbes ye
-i e -u: expediud o expedud, distribuud o distribud (in quel casu
pret. = cond.). Novial have volud (de un tema voli) ma volient. Si on
ne oblivia, que li max mult verbes es romanic, anc in Novial, on deve
preferer un excellent romanic auxiliare por li future: va amar, in
vice de «sal» (G soll), A shall o «vil», queles anc ha esset proposit,
nam tis es, in ultra, motiv-accentuat in li germanic lingues, quo «va»
ne es. Quam on vide, in comparation a Occidental li conjugation de
Novial ne es solmen plu ínnatural e arbitrari, ma anc plu desfacil e
ínregulari. — Novam ne conosse diferent tematic vocales, e pro to ne
posse formar li índispensabil verbal substantives e adjectives:
amator, finition, definitiv.

Yo da ci infra curt textproves:

NOVAM: Lua mala situo moje hud sat nolem decovrat si lua jemanta voco
ne hud revelat li yeste aftenone al New York Herald per il telefono.
«Come vu prenar por sender mi un reportoro? No, me nur bezonan algiu
por fraternizar, otra ca un garsono».

NOVIAL: Un objectione kel bli ofte fa konter konstruktet lingues es ke
les pove nulitem es tam boni kam li natur-lingues. Es ver ke novial
non es tam richi kam anglum, non tam eleganti kam fransum, non tam
vigorosi kam germanum, non tam beli kam italianum, non tam nuansosi
kam rusum, non tam hemali kam nusen patriali lingue.

// XXX NOTE -- li marca original de págine -131- esset in li sequent
// paragraf:

Li libre de prof. Jespersen contene curt criticas de Volapük,
Esperanto, Idiom Neutral, Ido, Latino sine flexione e Occidental. Lsf
il rejecte absolut, e it es interessant notar, que il attribue li
fiasco de Ido a du causes: 1) li principies del max bon auxiliari
lingue ne esset tractat «til fine suficent scientialmen», 2) li comité
e li «Akademio» de Ido ne esset suficent autoritativ. Pri Occidental prof.
J. di, que null project pos Esp. e Ido posse mesurar se in importantie
con Occidental. Ma il tamen ne es content con Occidental e critica it sur presc tri
págines. Un bon
critica es sempre salutat, si it monstra ver mancas, ma li critica de
prof. J. monstra miscomprension del cose criticat o es ínjust.

Il questiona p. ex., «Pro quo ne grandore, si on have longore?». In li
german e svedi claves de Occidental es mentionat grandore precis apud
longore. In Occidental existe li suffix -ore, quel, addit a adjectives,
indica mesura, grandore ne un qualitá in general, just quam in li
paroles grandore, longore, altore, largore; -ess indica qualitá
drasticmen emfasat o in traductet sense: grandess, altess, finess,
richess; -tá es li suffix por qualitá in general: granditá, altitá,
finitá, etc. e ti, qui ne pensa it necessi distinter inter -tá, -ore e
-ess (queles es internationalmen conosset sufixes) posse sempre usar
solmen -tá (ti, li max international sufix, manca in Novial). — Il di,
que Occidental es desfacil pro tis, qui ne ha ductet linguistic studias,
proque p. ex. ja in li alfabete c have duplic valore. Noi pensa que to
es un cose conosset ja in ante de omni cives del germanic e romanic
nationes, qui posse scrir e leer, mem li danes ne deve esser
linguistes por posse leer p. ex. citron e creme.

Al remarca de prof. Jespersen, que it ne es rational postular, que on
deve saver pluri lingues por aprender un auxiliari lingue, noi vole
dir, que it es anc nor opinion. Ma it sembla nos, que it ne es
rational suposir que on ne conosse su matrin lingue, e ínconsequent li
un moment suposir, que li homes save presc necos, p. ex. null cultural
lingue o null existent international paroles e lor scrition, e li
altri, que ili conosse «radicas» e «afixes», queles ya es electet, anc
in Novial, in conformitá a ti ultim suposition. Li existentie de du
simileant prefixes: ín- (accentuat, negation), e in- (li preposition
quam prefix) es un fact, quel on posse regretar, ma ne negar. Ili es
ambi international, e quo es international on ne posse evitar. Mem
Novial have les, ma secret: noi trova li parol «inosent», to es
comprensibilmen ín-nocent (G harmlos), quel in Occidental es un
totalmen regulari derivate, clarmen explicat secun li regules de Occidental;
ma in Novial it sta isolat, sin coherentie, in su ínnocentie
demonstrante, que li lingue ne cuida pri arbitrari decretes.

// XXX NOTE -- li marca original de págine -132- esset in li sequent
// paragraf:

In Occidental noi have li max natural e regulari derivation: logic, logico,
logica; grammatic, grammatico, grammatica; critic, critico, critica,
criticar. (Li síllabe -ic- es ìnaccentuat). Qualmen nu aspecte ti
paroles in Novial? Kritíke = critica, kritikiste o kritikére? =
critico, kritiki o kritikal? = critic e tu
kritika = criticar. In vice de criticisme, quel es in Occidental regulari
derivate con natural pronunciation, Novial deve haver o kritikisme,
quel es ínnatural, o kritisisme, quel es ínregulari, un parol isolat,
demonstrante, que li alfabete de prof. J. sempre va ducter a
complicationes e arbitraritás.

A li in omni punctus superior sistema de Occidental prof. J. fa ti remarca,
que on ne save, esque logica significa un feminin logico o un
scientie. Qualmen li povri lingues italian e hispan posse exister,
essent in li sam maniere ambigui?

// XXX FIXME -- I./It., H/Hi.:

Prof. J. cita, quam exemples de to, que Occidental malgré su tendentie a
natural derivation possede mult «ínnatural formes quam scrition,
analisation, interprension, descovrition». Scrition es scrit in It.
scrizione, ma pronunciat in sam maniere. Esque I. «scrizion» es
ínnatural? O esque Occidental «scrition» pro li t es ínnatural? In ti casu,
quant paroles es natural in Novial? Quo concerne analisation, noi
comprende necos. In Occidental on usa analise, e mem si on scri analisation,
pro quo ti parol, quel existe in li anglesi lingue in li sam form e
sense (vide p. ex. li conosset grand «Twentieth Century Dictionary» de
Chambers e altri autoritativ lexicos) es ínnatural? Interprension es
derivat de inter-prender (F entreprendre) e si It. e Hi. have. p. ex.
a-prension de a-prendere, pro quo ne inter-prension de interprender?
Ja in Lat. on format prehension de prehendere, de quel li modern form
es prender. Descovrition es derivat del verbe descovrir (F decouvrir,
A discover, I scoprire, H descubrir) e si natural lingues ha format
tal derivates quam I scopritore e H descubridor, pro quo Occidental ne posse
haver descovritor e descovrition, sin que on considera les quam
ínnatural?

Li principal remarca de prof. J. contra Occidental es to, que it ne es
suficent regulari. Quo es regularitá? Si ti postulation pri regularitá
significa, que on deve posser formar paroles secun li regules dat in
li grammatica del concernent lingue, quo ha fat prof. J. pensar, que
on ne posse formar regulari nov paroles in Occidental? In ti respect Occidental
have precis li sam possibilitás quam Novial.

// XXX NOTE -- li marca original de págine -133- esset in li sequent
// paragraf:

Ma contentar se solmen per un tal regularitá, vell esser povri. Vermen
regulari es un tal lingue, in quel ti paroles, queles on in fact usa,
e deve usar in international lingue, es format conform al regules del
grammatica. Ja in li curt textus dat de prof. J. il ha devet usar tal
paroles quam «tendentie», «diferentiatione», «inosent» e plu on va
scrir Novial, plu international
paroles on va esser fortiat inducter. Mult milles de ordinarissim
paroles va esser strangeres, ínregulari derivates secun li grammatica
de Novial, ma regulari secun li grammatica de Occidental. «Tendentie»
es in Occidental regulari derivate de «tender», ma un ínregularitá o un
strangere in Novial, e in sam maniere anc li altri citat paroles. Noi
vide in Novial un parol «emperere» in vice de Occidental «imperator», quel
Novial ne usa, ne possedente li sufix -or. Novial anc ne posse derivar
imperatori, imperativ, ma deve haver o emperali e emperivi, o
introducter li índispensabil parol imperativ quam contrabande. In Occidental
noi have «imperia» regularimen de imperar (sam quam dominia de
dominar, regnia de regnar etc.), ma ci Novial denove deve haver o
emperia, emperialisme, emperialist, emperialistali o introducter li
formes de Occidental «imperia, imperialisme, imperialist, imperialistic», sin
conexe con li cardinal parol.

Si li LI va esser un ver cultural lingue, e ne solmen un code por
expresser li simplicissim besonas, it ne posse omisser li ja existent
international vocabularium. Ma ti lingue, quel ne have international
derivation, anc ne have international paroles; e si it ne have
international paroles, it es fortiat crear arbitrari nov expressiones,
e quo es gravissim, rebaptisar li tot terminologie del scienties e
tecnica — un labor de Sisifos, ínutil e van. Existe anc li expedient
de Zamenhof: instituer un «§ 15», t. e. tra un detra-porta permisser
un invasion de international paroles, quam «strangeres» —
international paroles quam strangeres in un international lingue! Quo
on vell dir pri un dani lingue in quel li dani paroles es tractat quam
exceptional strangeres? Quam regulari, propri parol Novial ne have p.
ex. separator — ma separilo, ne duplicate — ma duoplate, ne
reduplication — ma riduoplo, ne essential — ma esali, ne qualitativ —
ma qualesivi, ne armatura — ma armisure, o simil formes in milles e
milles. Ma li publicat textus de Novial monstra, que li autor vole
permisser anc li international formes, queles ergo va esser in Novial
ínregulari exceptiones. Noi posse constatar, que si Novial vole esser
regulari, it va esser ínnatural, e si it vole esser natural, va esser
ínregulari. Li intention del autor de Novial hat esset presentar un
lingue plu regulari quam Occidental, in realitá su lingue es mult vez
plu ínregulari.

// XXX NOTE -- li marca original de págine -134- esset in li sequent
// paragraf:

Li labor del modern interlinguistica es triplic: tecnica, scientie e
arte. Li project de prof. Jespersen monstra nos, que
il ha dat attention exclusivmen al tecnica, e habilmen utilisat li
fructes e metodes de anteyan interlinguistes. It vell joyar nos
grandissim, si prof. Jespersen, con su rich e profund filologic
erudition, vell participar in li scientic exploration del material
base del LI, li existent international vocabularium e comun linguistic
fenomenes. Interlinguistica es anc arte, li estetic látere ne posse
esser negliget. Noi opine, que ti lingue, quel vole devenir li commun
spiritual vehicul por li nationes del occidental cultura, anc deve
star in contact con lor lingual customes e aspirationes e esser
atractiv por lor lingual sentiment.

_A. Z. Ramstedt_

// Un Progress? {{{2
=== Un Progress?

Li aparition de Novial demonstra li superioritá e vivicapabilitá del
idées de Edgar de Wahl, detalliat e exposit in li annucolectiones de
Kosmoglott desde 1922. In quelc detallies Novial apare quam un plu
minu bon imitation de Occidental, un Occidental in un nov edition. Támen it
es tre dubitabil que ti nov edition anc es un amelioration.

In li autor de Novial, li ancre multannual scientic de Ido, noi posse
vider un partialmen converteto, qui per su project public ha
confesset, que li via de il til nu sequet ha esset mal selectet.

Li finale -a ne plu significa li adjective ma li genere feminin, li -s
ne plu un finit verb ma li plurale, li -i ne plu plurale ma li
adjective.

Ma quo es quasi un coronation e sanction de principies de Occidental,
es li aplication complet del conjugation analitic. On posse respirar
plu facilmen ne plu vidente tam monstruos e strangi formes quam
skribesas, skribabis, skribesabis etc; noi vole esperar que tal formes
bentost va desaparir por etern, ili ne apartene ad un lingue quel vole
nominar se international.

// XXX NOTE -- li marca original de págine -135- esset in li sequent
// paragraf:

Apare me que per su Novial li partú conosset e estimat linguist plu ha
nocet quam subtenet nor comun idé. Necos de novitá valorosi in su
project posse defender li tro temporan publication: in contrari, li
novitás til nu publicat on totmen ne posse laudar. P. ex. li
elimination total del partú conosset e international usat líttere c.
Per un tal exilation on es fortiat continuar li mutilation de conosset
international paroles
til ínreconossibilitá e rupter heredat customes. Un international
pronunciation ne existe. Quam long va it durar til in li conscientie
va ear li conception, que ne li pronunciation ma preferabilmen li
scrition e ortografie es international? Pro ínegal pronunciation on
totmen ne have li jure anihilar li scrition usat in li tot munde.
Novial possibilmen oferta quelc vidpunctus util a imitar. Malgré to it
támen deve esser dit que Novial ha semat malherbe in li suficent
desfacil cultivat agre del interlinguistica, havente causat ne
altricos quam un statu de iritation inter li ánimes íncert e hesitant.

_Albert Haldin_

// Indiscret question a Senior Jespersen {{{2
=== Indiscret question a Senior Jespersen

Quande sr Jespersen, President del Ido-Academie, proposit in 1909
vicear «sed» per «ma», il dat quam argument to: «sed» es usat nu in
necun vivent lingue; it have li desfacil son d quem mult nationes ne
posse pronunciar corectmen in fine de paroles: li russes, li germanes
e li danes invariabilmen di set vice sed (vide «Progreso» II p. 14 e
anc mi «Ido justifié, p. 28). Ti ultim linguistic principie esset por
sr Jespersen tam important que il menaciat demissionar del Academie si
«ma» ne esset strax adoptet (Factmen sr J. demissionat quam presidente
li sequent annu pro li finales «-as, -is, -os»). Tre in colere, sr J.
questionat Couturat, quel oposit se al changeament de «sed»: «Esque li
Ido-Academie reconosse yes o no li principies scientic del
linguistica?»

Ma, sr Jespersen, si li «scientic principies» del linguistica ne
permisse adopter un finale «-ed», quel mult nationes ne posse
pronunciar correctmen, tande Vor perfect per «-ed» in Novial es mal,
tre mal! Mult nationes va pronunciar: me eset, me propagat, e sr J. va
esser fortiat denove demissionar de su futur academie. Pro que sr J.,
quam il self confesse it, mult aprendet de sr de Wahl, yo vell
consiliar le prender de il ancor su perfect per -t, e scrir: me esset,
quo es conform al max facil pronunciation del «mult nationes».

_Ric. Berger_

// Citate {{{2
=== Citate

// XXX FIXED -- Li titul "Citate" esset mettet in ti edition.

[quote, Lincoln]
____

Vu posse dupar li tot popul durant quelc témpore, e un parte del popul durant li tot témpore, ma vu ne posse dupar li tot popul durant li tot témpore.

____

// XXX NOTE -- Ci esset li marca original de págine -136-

// Cronica {{{2
=== Cronica

S. A. P. O. (Sviss Association por Occidental) sub li energic duction
de president sr Ric. Berger e secretario sr Fred Lagnel desde su
fundation ha fat admirabil successosi labores. Li Association edite
por su membres un mensual «Bulletin de S. A. P. O.» (actualmen
consacrat precipue a discussion del question: Ido e Occidental). Adplu
ha aparit divers folies volant, documentes (til nu: 1) Aux amis de la
L.I., 2) Pourquoi l’Occidental emploie-t-il des accents?, 3)
L’Occidental a-t-il trois infinitifs?, 4) Pourquoi l’Occidental
conserve les doubles consonnes), adplu: Correspondentie inter Ric.
Berger e L. de Beaufront e inter Ric. Berger e L. Leau, Raport de A.
Creux pri Ido e Occidental al Romanda Ido-Societo etc e un «Cours
d’Occidental par lettres leçons» (til nu: 2 lettres). Pro manca de loc
noi ci ne posse raportar plu detalliat pri omni ti tre interessant e
propagativ editiones de nor nov brav colaboratores. Noi invita nor
letores qui desira reciver li folies, misser adminim 2 francs sviss
al: Occidental-Buro Fred Lagnel, Chapelle (Vaud), Svissia;
Postchec-Conto: II. 1969.

Cosmoglotta in Mauer bei Wien havet li visita de du extern samideanes,
li 5—7 mai de sr Dr. Ing. Arthur Wormser-Frankfurt a. M. (autor del
Ido-lexico «Mashinelementi e ordinara utensili»), li 22—26 junio de sr
cand. med. Bengt Hammar, president del Ido-Club Stockholm.

«Der Fremdsprachler» (jurnal por cultivation de lingues,
administration: Franz Wessel, Berlin No 18, Landsberger Str. 113),
juli, publicat un articul propagativ por Occidental: «Evolution del
idé de Lingue International», con textus comparativ in Esperanto, Ido
e Occidental. Li maniere de propagande es tre impressiv e totalmen nov
por li neutral publica; ad saver, li articul es scrit in Occidental
self e sublinea li fact que «Occidental es inmediatmen comprensibil a
omni hom de occidental civilisation». Quel del artificial lingues nu
va posser imitar ti maniere de propagande iniciat per Occidental?

«L’Idée libre», Conflans Honorine, raporta pri li brochure
«L’Occidental, Langue d'intercompréhension immédiate» de L. M. de
Guesnet.

Anc «Heroldo de Esperanto», nr 22, contene un curt noticie pri ti
aparition e pri «Occidental-Bulletin» (Ocasional Circulare pri
Mundlingual afferes, de Ferguson Press, Jeffersonville, Indiana, USA).
Sr T. J. rejeta li criptogrammas «nepri, malanigi, obligi», por queles
Esperanto have li international formes «persisti, ekskludi,
multipliki». Por li du ultim on trova in Esperanto adver: «eksigi» e
«multopligi».

// XXX NOTE -- li marca original de págine -137- esset in li sequent
// paragraf:

Intern del organisation de UEA (Universala Esperanto-Asocio) ha
eruptet un revolte. Li chef delegat de UEA por Francia, Georges
Delanoue (4, rue Charles-Divry, Paris XIV) contra li precie de 1 sviss
franc por 6 exemplares, dismisse «Al la Esperantistaro» public
circulares printat con sensational «revelationes». Il cita alarmant
verdictes de conosset esperantistes de divers landes, delegates e
membres del Esperanto-Academie (Dr. P. Corret-Paris, M. W.
Page-Edinburgh,
Prof. Dr. Vanverts-Lille, Jaume Grau Casas-Barcelona, Prof.
Cart-Paris, Prof. Dr. Dietterle-Leipzig, Grosjean-Maupin-Pany, etc)
contra li centrale in Genève, a quel ili reprocha «skandalan
malfidelecon» a Esperanto. Li reprochas directe se anc contra li
person del presidente de UEA, Dr. Privat. On acrimen critica que li
central organ ha permisset se sin aprobation del Esperanto-Academie,
scrir li nomines landal per -io vice -ujo. Li conosset feroci
adversario de Ido e nu de Occidental, delegat Dr. Spielmann-Bern, in
li sam circulare replica que «suficent fervoros Esperantistes ja desde
long postula li absolut necessi reformas por finalmen mortar Ido e
Occidental e ducter Esperanto til secur victorie. On ne mey ataccar sr
Privat tam ínamicalmen». Karl Minor-Hamburg, membre del «Lingva
Komitato», in contrari advoca boicottar li organ de UEA, nam un
«jurnale tam dangerosi por li lingue Zamenhofan on ne mey subtener per
abonnament». Prof. A. Dombrowski-Littovia, membre del Esp-Academie,
conclude que «li sol practic remedie es li elimination del actual
presidente e li election de un altri ver fidel chef del chefes».

In sam témpore in «Heroldo de Esperanto», nr 19, aparit un articul de
Izrael Lejzerowicz in quel il acusa li provocatores del «uragano»,
quel che mani esperantistes evoca li idé que un nov «Beaufronterie»
bentost va evenir. Il peti tacer nu nam «nor adversarios
(kontrauuloj), li idistes e occidentalistes, certmen bentost va far
bruida que Esperanto es menaciat del debacle …»

Li central organ «Esperanto», Genève, junio, responde al mentionat
acusas public e P. E. Stojan presenta un elaborat in quel il con grand
diligentie demonstra que li membres de UEA procede plu papal quam li
papa, nam p. ex. li sistema de Zamenhof pri li nomines del landes,
secun mult exemples colectet de sr St., esset ínsistematic.

Li redactor de «Heroldo de Esperanto», sr Teo Jung, in su nr 16
publica un lettre quel il ha recivet del presidente del UEA, u li
ultim expresse li espera que li proposition de sr T. J. pri un
intersistematic transaction nu es finit, nam un tal demarche, il di,
es «certmen mult plu grav e dangeros quam li usation de international
nómines landal»!

In li sam numero es publicat anc un lettre de sr de Wahl a «Heroldo»,
i. e. un response al lettre de prof. Christaller in nr. 9, 10
(recenset in Cosmoglotta nr 48, pag. 79) con un comentarie de sr T.
J., finient per: «… Ambi lingues es genial elaborates de genial
mentes. Li cardinal diferentie es, que Esperanto vive ja quar
decennies, durant que Occidental jus ha nascet. Noi do vole atender li
evolution».

// XXX NOTE -- li marca original de págine -138- esset in li sequent
// paragraf:

Li Esperanto-presse es embarassat per un decrete recentmen editet del
ministre de instruction in Bulgaria, in quel il interdicte al scolanes
aprender Esperanto e reciver jurnales in ti lingue artificial. Per ti
nov decrete de 1928 li ministerie oficialmen anulla un altri tal de
1920 in quel it ha recomendat Esperanto. «Bulgara Esperantisto», nr 9,
crede har divinat li cardinal causes del interdiction: «Pro que
Esperanto es un facil lingue, li disciples va acustomar se li
facilitás e va perdir li inclination a aprender plu desfacil aferes.
Pro que Esperanto es international, li disciples va comensar estimar
li internationalisme e desestimar li national lingue e cultura;
finalmen li movement de Esperanto es suspectet, que sub it cela se
elementes ínamical contra li state».

Secun «Heroldo de E.», nr 20, anc li ministre por intern afferes in li
hungarian parlament ha refusat un propose del deputat Frühwirt
demandant que li functionarios del policie mey aprender Esperanto.

Un amusant specimen de zelotisme noi lee in «Germana Esperantisto», nr
387, editet del conosset firma «Rudolf Mosse», Berlin. In su raport
pri Novial li redactor scri: «Ja li nómine de ti nov conglomerat fa
divinar que it es un miscreation … It es temerari, voler atinger o
superar li lingue de Dr Samenhof in punctu de internationalitá del
vocabularium e simplicitá del grammatica. To noi Esperantistes posse
asserter sin presumption. Combatter por to noi debi a nor genial
Mastro e a omnis qui garda su heredage. Versemblabilmen li tracies de
Ido, quel posse ni viver ni morir, e ti de altri ínutil «idoj», quel
pos curt pseudovive, fini lamentabilmen, ne sufice, por deterrar del
procedentie sin chances, voler detronisar Esperanto. Lu max regretabil
de ti afere es, que on deve mem ocupar se pri it, pro que li jurnales
dial raportant pri ti nov trubla, denove introducte confusion in li
circules ancor ne esperantistic. Malgré nor intern conviction pri li
ínvictibilitá del idé de Esperanto, noi tamen deve gardar nos contra
li nov adversario …»

_E. Pigal_

// Criterie de L.I. {{{2
=== Criterie de L.I.

Prof. A. R. Nykl del Marquette University, Milwaukee, Wisconsin, U. S.
A. publica un articul «Brevety as a criterion of language» in li
«American Journal of Philology», Baltimore, Maryland.

Quam ja monstra li titul, li autor apologisa quam fundamental e quasi
unic principie por un L.I. su curtitá: «Li max bon international
(auxiliari) lingue es ti quel posse expresser max mult idés in li max
curt via, clar e acuratmen, per medie de un facil articulation».

Por soluer li question quel lingue es max apt e conform a ti
principies il submisse 72 divers lingues a un comparativ exploration
quel consiste in li traduction de du curt frases: 1) I see a good
man’s hand, e 2) I can run better than my father, electet secun divers
principies, quo deve contener un proposition grammatical por monstrar
omni grammatical relationes. Li autor nu conta li númere del síllabes
e quáncam li max curt vell esser antiqui-egiptian e poy modern
irlandés, veni al conclusion que li lingue angles es li max curt e pro
to max bon por un L.I.

// XXX NOTE -- Ci esset li marca original de págine -139-

Por verificar li resultates de ti unesim prova il controla to per un
coherent text por quel il electet li patre-nostri, e contante li
síllabes veni al sam resultate.

Poy il compara ancor Esperanto e Ido con angles e monstra que anc ci
angles have li avantage. Li Esperanto usat monstra mult erras. Anc li
textes in li divers lingues ne es absolut secur, p. ex. li texte russ.

Il conclude que li max bon artificial lingue ne posse con success
concurrer con li max evoluet natural lingues angles e frances, e in li
venient 500 annus angles e frances va atinger un tal perfection, quam
ni un sol lingue artificial ne posse jamá haver li espera atinger.

It es un bon simptoma que li scientistes comensa interessar se pri li
tema de un L.I., specialmen li americanes. De altri látere on vide que
mem li scientie official ea li sam via quam li dilettantic practica.
Prof. Sapir e prof. Nykl ambi per su opiniones publicat monstra que
ili sta ancor in li embrional statu relatente li L.I. A ili li idés
expresset per mag. A. Z. Ramstedt in su profund articul «Psicologic e
sociologic caractere del L.I.», (Cosmoglotta 1927/2, 3) es ancor
absolut ínconosset. Por advenir a ti maturitá li practic dilettantic
movement ha besonat 50 annus. Noi mey esperar que li scientic movement
va advenir al agnoscion de ti fundamental principies in li venient 5
annus. Forsan tande va esser possibil un rasonabil collaboration.

_E. W._

// Quelc opiniones de sviss Idistes {{{2
=== Quelc opiniones de sviss Idistes

Dr. Aschwanden, med. oc., president del Ido-gruppe de Biel: «Pro que
yo es persuadet que Occidental es un ver e grand progress in li
mundlingual movement, que it es li max bon solution experit til nu e
que it forma li fundament sur quel omni mundlinguistes vell posser
unir se, yo declara mi adhesion a Occidental. … Li letura del numeró festiv
de Cosmoglotta esset por me un ver revelation e Vu mey esser cert que
noi, ex-idistes in Biel, va laborar por li solution del L.I. in li
sense de Occidental»

Dr. Schrag, inspector de secundari scoles, Bern, autor de un
aprension-libre por Ido, publicmen declara Occidental un grand progress.

Dr. H. Nidecker, pres. del «Suisa Ido-Federuro» scri: «Occidental sona plu
natural quam Ido, sin esser minu regulari. In Ido, certmen, li
radicarium es international, ma in Occidental anc li grammatica. … Si pos
studia, yo trova que Occidental es plu perfect e plu facilmen comprensibil
del max grand númere de nationes, yo nequande va hesitar pri adoption.
Ne importa li nómine, importa solmen li idé e su realisation.

Junio 1928.

// XXX NOTE -- Ci esset li marca original de págine -140-

// Textu comparativ {{{2
=== Textu comparativ

Quam textu comparativ on usa ordinarmen li Patre Nostri. Ma ti prega
have li desavantage que li max mult verbal formes usat in li textu,
sta in imperative. Ergo it vell esser plu bon selecter un altri textu
contenent verbes almen in li tri témpores cardinal del active, adplu
substantives usat in li quar unesim casus, e tam mult formes quam
possibil del pronómines personal.

Pro que yo intente traducter un tal textu in li lingues max important
(e natural e artificial), yo peti omni coidealistes por far
propositiones relatent al selection del nov textu comparativ. It posse
esser un textu composit por ti scope o prendet ex un ovre litterari
conosset generalmen. Yo vell preferer ti ultim solution. Ma li textu
ne deve esser plu long quam ti del Patre Nostri.

_Karl Janotta, Kaltenleutgeben (Austria)._

// Noticies {{{2
=== Noticies

Ido-Congress Zürich. Mersí al auxilie de nor fervent colaborator sr
Ric. Berger, presidente del Sviss Association por Occidental
(Corcelles près Payerne, Vaud), noi posse inserter in li present
numeró un serie de articules consacrat specialmen al partiprendentes
del Ido-Congress in Zürich, 2—5 august. Noi espera que ti articules va
contribuer al claration del conceptiones de ti de nor idistic
samideanes queles pos li ultim evenimentes in li movement de Ido ancor
ne ha decidet se quel direction ili nu va electer.

«Naturaleso e Artificaleso». Pro manca de loc, li response de sr de
Wahl a ti articul in «L’Idiste Français» nr 30, 31 e al articul de sr
Houillon in «Idisto Katolika» nr 5, 6, va aparir in li sequent numeró
de Cosmoglotta. Singul ne-abonnat Idistes exceptionalmen posse reciver
ti nro 53, gratuitmen, si ili demanda it explicitmen che:
Administration de Cosmoglotta, Mauer b. Wien.

Visita in Wien. Li officie de Cosmoglotta in Mauer (Hauptstrasse 51.
Telefon: Atzgersdorf 558) es atingibil per tramvia 60, del centre in
un hor.

Unesim official conferentie international por Occidental va evenir in
august 1929 probabilmen in Paris. Ples misser relatent proposes a:
Cosmoglotta, Mauer bei Wien.

Complet annu-collection 1927 de Cosmoglotta. Quelc exemplares ancor es
recivibil, contra 1 Dollar (7 ö. S.). Li singul cadernes de 1927 ja es
exhaustet, exceptet li numerós de septembre til decembre.

Lexico German-Occidental de J. Gär pro plurimensual bastament (A
strike, F grève) del laboreros in li printería in Reval retarda se. Li
complet ovre va aparir probabilmen in octobre.

_E. P._

// XXX TODO -- Titular:

Eigentümer, Herausgeber u. Verleger: Gesellschaft Cosmoglotta, Mauer
bei Wien, Verantwortlicher Schriftleiter: Ing. E. Pigal, Liesing bei
Wien. Druck: Milan Nedvídek, Tábor.

// Cosmoglotta A 068 (jan-feb 1930) {{{1
== Cosmoglotta A 068 (jan-feb 1930)

COSMOGLOTTA

Oficial organ del Occidental-Union

Consacrat al developation, propaganda e aplication de

Lingue International Occidental

Redaction e Administration: Postlach 10, Mauer bei Wien, Austria.

Annu IX Nr 1    Januar, Februar 1930   Numeró 68

// Contene {{{2
=== Contene

- Cronica, pg 1.
- Oficial comunicationes, de Central Oficie, pg. 5
- Regulamentes (Comité Linguistic, Academie), pg. 7
- Interlinguistic reminiscenties II, III, de E. de Wahl, pg. 11
- Corespondentie, de Heinrich Loft, pg. 18.
- Pro quo noi studia historie, de J.L. Maddox, pg. 20.
- Foren lingue, de K. Janotta, pg. 22.
- Fabul, de Klabund, pg. 22.
- Record de rapiditá, pg. 23.
- Reclame, de Joh. Frank, pg. 23.
- Subventiones, pg. 24.
- Avises, pg. 24.

// Cronica {{{2
=== Cronica

// Libres {{{3
==== Libres

OCCIDENTAL, DIE WELTSPRACHE. Einführung samt Lehrkursus, Lesestücken,
Häufigkeitswörterverzeichnis, u.a. Beiträge von E. Graber (Dresden),
K. Janotta (Kaltenleutgeben), E. Pigal (Mauer bei Wien), J. Prorók
(Leipzig), Mag. phil. A. Z. Ramstedt (Helsingfors) und E. v. Wahl
(Reval). Herausgeben von E. Pigal durch die Haupstelle der
Occidental-Union in Mauer bei Wien, Franckhsche Verlagshanglung,
Stuttgart 1930. -- 256 SEiten in Normformat A 5 (148 x 210 mm).

Preis: geb. RM 8,- (ö. S. 13,70), brosch. RM 5,50 (ö S. 9,50).

Ex li contenete (traductet fro german): Vias e abvias al mundlingue,
de E. de Wahl. Essentie de Occidental, de E. Pigal. Cultural e
pedagogic valore de Occidental, de J. Prorók. Motivation, de E. de
Wahl. Occidental-curs in 10 leciones de Mag. phil. A. Z. Ramstedt.
Repetitorie del grammatica in Occidental, de Karl Janotta.
Vocabularium del 1000 frequent paroles (Occidental-Deutsch e
Deutsch-Occidental) de E. Graber. Leturas in Occidental. Textus
comparativ in 9 lingues, etc.

Li prefacie es precedet per li conosset motto propagativ secun Albert
Lecomte. Li unesim articul de Wahl es un analisant historie del
mundlingual tendenties, depos li antiqui témpores til hodie, con
special egard al anglés, latin, Volapük, Esperanto, Ido e Novial. Li
duesim articul de Wahl (Motivation) presenta justificationes de apart
formes de Occidental e completa li tractate de Pigal, quel es
augmentat e ameliorat conform al articul sub li sam titul in
Cosmoglotta nr 45. Pri li excellent Occidental-curs arangeat secun li
recent pedagogic experienties e exemplificat per tre interessant
leturas de distint qualitá, ja esset raportat plur vezes in altri locs
de Cosmoglotta.

// XXX NOTE -- Ci esset li marca original de págine -2-

Li repetitorie del grammatica es scrit in Occidental self con li
intention ne solmen dar un resumé del curs de Ramstedt, ma anc exercir
li adept pri li letion del linguistic articules in ti libre e in
Occidental-revúes. In fine li ovre contene enunciationes de
competentes pri Occidental in textus paralel, Occidental e german,
adplu avises pri movement e litteratura.

Li dictionarium del sistematicmen selectet 1000 paroles max frequent
es un fonte unic til nu por lexicografos de omni lingues. Li unesim
vocabularium scientificmen elaborat secun frequentie del paroles esset
fat por li german lingue (Häufigkeitswörterbuch der deutschen Sprache,
Festgestellt durche inen Arbeitsausschuss der deutschen
Stenographiesysteme. Herausgegeben 1897 von F. W. Kaeding. Wort-,
Silben- und Buchstabenzählung, Verlag: E. S. Mittler & Sohn, Berlin
SW, Kochstrasse 68..71). Por li L.I. anc Joseph Weisbart in su
abecedarium ha composit un tal vocabularium del paroles usual in hem e
ordinari comunication oral. Ma li vocabularium de E. Grober selecte e
ordina li frequent paroles (presc li sam in chascun europan
cultur-lingue) secun li actual besones del interlinguistes, i.e.
precipue per scrit, in epistules, jurnales e libres.) 1

Li original vocabularium, li leturas e li repetitorie del grammatica
in Occidental have interesse ne solmen por nov Occidental-interessates
e comensantes, ma anc por occidentalistes perfect e non-german.

Ti libre ligat in elegant vestiment, velopat in un artistic covriment
protectiv, es li unesim plu grand ovre quel contene in maniere
sistematic e detalliat un complet colection del conceptiones del
occidentalistes e del regules e formes usual del sistema Occidental.

Li Central Oficie e su colaboratores ha plenat su promesse. Li max
grand mersias pro erection de ti monument in li historie del lingue
international merite li reputat editoría e specialmen su clar-vident
chef senior Hefrat Walther Keller.

Nu apartene al occidentalistes utilisar li instrument posit in lor
manus. Ples hauster nov entusiasme ex li págines del libre, ples
iniciar pensant e actent homes studiar it por que ili recive claritá
in li actual statu del problema e por que ili aquisite un bon
conossentie del lingue Occidental.

Li libre es recivibil anc per li Administration de Cosmoglotta.  -i-

// XXX NOTE -- Ci esset ti separator: ----

1) Li 1000 max frequent paroles representa plu quam 3/4 del current
lingue! Ti fact deveni credibil si on save que li 15 max frequent
paroles representa circa 1/4 del tot lingue, quo chascun letor self
posse constatar per un simplic statistica fat por exemple ex li
paroles de tri págines de Cosmoglotta pri divers temas. Secun E.S.
Holden e E.H. Babbitt un modern erudit hom save 30 000 til 60 000
divers paroles. Secun W. Wundt un infant usa circa 1000 divers
paroles. Illias e Odissé junt have 9000 divers paroles. Secun K.
Lokotsch li richesse del dictionarium de Shakespeare per su 20 000
paroles es un record.

// XXX NOTE -- Ci esset li marca original de págine -3-

COURS COMPLET D'OCCIDENTAL, de Ric Berger. Editoría: Occidental-Buró.
Chapelle-Vaud (Svissia), brochura de IV + 64 págines, 220 x 180 mm,
precie sv. fr. 0.50.

Ti grammatica con exercities por franceses esset fat tre habil, malgré
que li sones mollat es evitat complet per formes anc criticabil: on
usa atiner, ferral(l)ia etc. Nor fervorosi coidealist sr L. Ravasse,
exoficero del francés marine, chevaliero del Legion de Honore, oficero
del Coron de Italia, ha scrit li introduction, ex quel noi remarca li
du sequent passus: "Li demonstration que Esperanto es plu facil quam
Occidental, resta a far" ... e: "Li scope del lingue international es
... servir quam medie de intercomprension eficaci a omni teles,
comerciantes, industriales, politicos, scientistes etc. por queles li
relationes international constitue un necessitá. Pro to it es necessi
que li lingue auxiliari es in lor nivelle intelectual, e ne in li
nivelle del inteligentie rudimentari del populationes savagi ..." In
214 paragrafes li essentie e construction de Occidental es explicat e
demonstrat passabilmen exhaustiv. Li regules de pronunciation es
tractat suficent in detallie e con precision. Presc un ters del
contenete es dedicat a exercities de traduction, quo es tre util por
franceses queles, essente seductet per li romanic exteriore de
Occidental, altrimen vell sin hesita aplicar gallicismes. Li curs es
scrit con tant elan e verve que li letor certmen va studiar it con
interesse crescent de un paragraf al sequent. It representa ne solmen
li max complet aprense-libre, quel noi possede in lingue francés, ma
it certmen va esser anc un bon e efectiv propagative. LI autor e su
colaboratores merite gratulation e mersias.    A.D.

// XXX NOTE -- Ci esset ti separator: *

Li sved calendare NYKTERHETSFOLKETS KALENDER contene por 1930 un long
articul pri li mundlingual question de Docente Dr. C.W. von Sydow,
presidente honorari del Occidental-Academie e presidente del Sved
Occidental-Federation. In un tre objectiv maniere es tractat li
historic evolution del lingues international, li hodial representantes
e lor merites e defectes. Li superioritá de Occidental es accentuat
specialmen por li scientie e li comercie.  C.E.S.

// Jurnales {{{3
==== Jurnales

HELVETIA, organ del Sviss Association por Occidental (SAPO), nr 12
(19), decembre 1929, Occidental-Buró, Chapelle (Vaud), Svissia
(Postchec-conto: II, 1969: Fred Lagnel, Chapelle, Vd.): abonnament por
1930: Svissia: sv. fr. 2.-; extrania: sv. fr. 2,50. Ex li contenete:
Noi avansa! (nov membres), Occidental-Academie. Extraordinari
experientie (un mann quel aprende Occidental in quelc hores e sin
grammatica!). Document historic de grand valore (Un epistul de sr de
Wahl pri li project Auli), Anecdotes, poemas, reclame etc.

INTER NOS, bulletin mensual del British Occidental Society. 18,
Meadows Lane, Chester (Anglia), nr 3, decembre 1929: The Outlook (li
perspective), li folie raporta pri li actual situation e expresse bon
desiras por 1930): curt noticies; anuncias. Li redaction informa que
in li proxim numeró del revúe va aparir un articul de sr de Wahl.

// XXX NOTE -- Ci esset li marca original de págine -4-

LA GAZETTE COMMERCIALE, Paris, 28-m annu nr 1, 11 januar 1930. Sr. L.
Ravasse descri li desfacilitás del international comprension in li
comercie e proposi quam sol possibil solution li adoption de
Occidental. Li articul fini per un propose de sr Dr. Nidecker,
presentar al international comercie reclames in Occidental.

LA CHRONIQUE ARTISTIQUE, Paris, 7 decembre 1929, continua li
discussion pri li L.I. per un articul de L. Ravasse motivant pro quo
li autor prefere Occidental a Esperanto, e reproducte li image de sr
de Wahl. Sr Maurice Duval prova defender Esperanto in un long epistul
al redaction. In li numeró del 4 januar li revúe insertet un articul
de L. Ravasse refutant li esperantistic argumentes in maniere
irrefutabil. Lu sam fa sr René Depin in un epistul al redaction; il
insiste precipue sur li opiniones del comité del «Delegation por
adoption de un Lingue auxiliari». de professor Meillet del «Collége
de France» e del «Commission de Cooperation intelectual del Societé
de Nationes», queles omni refusa Esperanto.

L'ALSACE ILLUSTRÉE, 9 novembre 1929, Mulhouse, contene un articul de
sr. L.M. Guesnet. Il di inter altricos: «Occidental have un camp de
action enorm. On posse usar it strax por li comunicationes e persones
queles ha aprendet it nequande, queles mem ne conosse su nómine.»
Jtt.

LE TEMPS, Port au Prince (Haiti), 8 octobre, insertet un articul por
Occidental.   L.M. de G.

NORTH CHINA STAR, Pekin, 11 novembre 1929, contene un articul pri
Occidental sub titul con grand lítteres «Occidental stands chance of
becoming universal language» (Occidental have chance devenir
universal lingue). It es important que ti jurnal in lontan oriente
nomina Occidental li «universal idioma de pace». On constata que li
grammatica es tre simplic e facil. Un textu in Occidental fini li
impressiv articul.   Jtt.

«A bis Z», comunicationes por Scheithaueran stenographos, 1930, nr
1, inserte un curt textu por Occidental, tre recomandabil in populari
propaganda in landes precipue non-romanic e nonanglés, ma in li lingue
national. «Li lingue Occidental es un extract del international
extran paroles ex li europan lingues. Qui es versat in lingues
(sprachgewandt), ti comprende Occidental immediatmen. Qui ne es versat
in lingues, ti aprende per chascun parol Occidental un parte (Stück)
del europan cultura quel il ancor indige, e il talmen participa al
tresores del international civilisation mental (Geistigkeit). Manuales
es recivibil per adresse: ...»   E.P.

SENNACIULO, organ del S.A.T., association anational del  esperantistic
laboreres, pag. 178, have un articul quel vell demonstrar li plen
dissolution de Esperanto si it ne es solmen un momentan deviation. Sub
li titul «Atentu spiriton, ne sole literon de Fundamento!» on
postula inter altricos li sequent novitás, introduction del sufixes
-al, -i e -oz, con li sam sens quam -al, -i(e), -os(i) in Occidental.
Tal innovationes adver vell changear plenmen li lingue de Zamenhof.

// XXX NOTE -- Ci esset li marca original de págine -5-

BERLINER TAGEBLATT, Berlin, nr 3, 2. jan. 1930, contene in articul «
Die Technifizierung der Verständigung» (Li tecnification del
intercomprension) de B.F. Dolbin. Ti articul es o un ver persiflage de
Esperanto o un demonstration que li autor ne conosse Esperanto; on ne
posse suposir li duesim possibilitá, nam li jurnale apartene al firma
Mosse, quel esset til recent li cardinal editoría del german
esperantistes. Li autor nomina li Esperanto-traduction de «
Meistersinger» (maestro-cantatores) de Richard Wagner un mal
experiment e reputa Esperanto quam ínapt por li poesie. Li sonette «
Bonvenon in Wien» de Fr. Zwach, il nomina un «liric malore». Il
postula li amelioration de Esperanto, quel have defectes queles deve
esser abolit. «A ti lingue-edificie solmen su purification fro li
mercantes conserva li spiritual consacration. Li proxim
Esperanto-congress mey efortiar pri li problema dar li índubitosmen
tecnic form al tecnic medie de intercomprension». Anc ti autor
postula li self-dissolution de Esperanto, in li prominent jurnale,
quel ante poc mensus ancor esset conosset quam max remarcabil
protector de Esperanto.   Jtt.

// XXX NOTE -- Ci esset ti separator: ----

// Occidental-Union {{{2
=== Occidental-Union

*Organisation Universal de Lingue International Occidental*

==== Official comunicationes

// XXX NOTE -- li marca original de págine -6- esset ante listune "(2)
// Patronate":

===== I. Decisiones

Li constituent membre-organisationes del Occidental-Union ha decidet
conform al Statute del Union (vide Cosmoglotta nr 55) por:

(a) Contribution annual por 1930:

(1) Chascun membre ordinari (i.e. organisation, vide articul 4 del
Statute) paya 1/2 dollar por chascun complet o comensat 20ene de
membres queles ti membre have.

(2) Membres extraordinari (articul 5) paya adminim 2 dollares.

(3) Adherentes individual, existent solmen in landes sin section
national del Occidental-Union, paya 1/2 dollar.

(4) Chascun membre o adherent recive li oficial revúe gratuitmen in
tant exemplares quant il paya 1/2 dollar al Central Oficie.

(5) Membre-contributiones al Occidental-Union deve esser explicitmen
designat quam tales. Un abonnament del revúe ne implica li jures de
membre.

(b) Functionaries:

(1) Protectores:

Dr. J. BAUDOUIN DE COURTENAY †, Professor de Linguistica, Universitá
de Warszawa, Polonia; Dr. Albert GUÉRARD, Professor de Litteratura
General e Comparat, Universitá de Stanford, California, USA; Dr.
Albert SAARESTE, Professor de Litteratura, Universitá de Tartu
(Dorpat), Estonia.

(2) Patronate:

Hoirat Walter KELLER, Stuttgart, Germania: Louis RAVASSE, Paris,
Francia.

(3) Presidentes honorari:

Ing. Hanns HOERBIGER, Mauer bei Wien, Austria; General-Director Gerald
A. MOORE, London, Anglia.

(4) Senate:

Provisori Presidente: Ing. Hans HOERBIGER; Vice-presidentes: Prof.
Ric. BERGER, Morges, Svissia, e Dr. A. PEIPERS, Köln, Germania. Céteri
membres: L.M. de GUESNET, Paris, Francia: Albert HALDIN, Eskilstuna,
Svedia; Reg.-Rat Dr. MELL, Rudolstadt, Germania; Mag. phil. R. REHN,
Helsingfors, Finnland; Comte Dr. E. ZICHY, Komárom, Hungaria.

(5) Central Oficie, Mauer bei Wien, Austria:

Director e Redactor: Ing. Engelbert PIGAL (EP); Secretario: Karl
JANOTTA (Jtt); Administrator: Cand. comm. dipl. Maria MIMRA (MM).

(6) Academie:

Presidente honorari: Prof. Dr. C.W. von SYDOW, Lund, Svedia: Membre
honorari: Edgar de WAHL, Reval, Estonia (EW); Presidente: Prof. H.
PÁSMA, Tábor, Tchecoslovacia, (Pa); Vice-presidente: Dr. Ing. Artur
WORMSER, Offenbach a., M., Germania (Wo); Secretario: Ing. E. PIGAL,
Mauer bei Wien, Austria (EP); Membres: Dr. ASCHWANDEN, Biel, Svissia,
Eric BIDDLE, Chester, Anglia, Dir. G. BOHIN, Strasbourg, Francia, J.
CASSE, Köbenhavn, Dania, A. CREUX, Rue, Svissia, A. DEMINGER,
Düsseldorf, Germania, Joseph GÄR, München, Germania, K. JANOTTA,
Kaltenleutgeben, Austria, J.A. KAJS, Brno, Tchecoslovacia, Dr. K.
SCHÜPPEL, Parchim, Germania, Dr. C.E. SJÖSTEDT, Upsala, Svedia.

(7) Comité linguistic (Celia).

Presidente e Redactor: Dr. A. WORMSER, Offenbach a.M., Germania (Wo);
Secretario: A. DEMINGER, Düsseldorf, Germania (AD).

// XXX NOTE -- li marca original de págine -7- esset in li sequent
// paragraf:

Pro mult ocupationes professional sr Mag. phil. A.Z. Ramstedt devet
demissionar quam secretario del Celia. Noi tre regreta ti decision de
nor estimat coidealist, quel ja mult avansat nor comun labores, tam
per su activitá linguistic quam per li composition de su modellic
Occidental-curs in li german libre «Occidental, die Weltsprache»
(OdW). Ma Mag. Ramstedt continua consacrar su interesse a nor idé e
anc su activ participation al movement per restar membre del Comité
linguistic. Dr. Wormser e sr Deminger havet li amabilitá prender sur
se provisorimen li redaction respectivmen li secretariatu de Celia. Li
du coidealistes ja es bon conosset al occidentalistes per lor
successosi labores por Celia. Dr. Wormser nu va anc presider Celia,
pos que sr de Wahl quam autor de Occidental es e membre honorari del
Academie e ergo anc de Celia e ne vole influer quam presidente li
líber decisiones del du comissiones e self anc desira un plu grand
índependentie in expression de su linguistic
opiniones, quo forsan esset minu possibil quande il esset presidente
de Celia.

Noi mersia omni colaboratores pro acceptation del functiones por
queles li Plenum del Union ha electet les. Nu, pos final constitution
li nov annu mey devenir fructosi in li comun servicie por li pensa
occidentalistic.

===== II. Adhesiones

Organisationes queles vole devenir membres del Occidental-Union, deve
demandar del Central Oficie un formulare de declaration de adhesion.

Li membres del Union mey demandar del Central Oficie li necessi númere
de oficial legitimationes del Union por lor individual membres.

Noi torna li atention al articul 5 del Statute (publicat in
Cosmoglotta nr 55), secun quel omni persones juristic (i.e. autorités,
corporationes, firmas, etc) posse devenir membres extraordinari si ili
obliga se responder in Occidental a teles de lor corespondentes queles
demanda it. Lor contribution minimal in annu es 2 dollar secun punctu
I, a in supra. Omni occidentalist es invitat recrutar membres
extraordinari por li Union. Li jures de ti membres on trova in li
articules 7 e 12 del Statute.

===== III. Regulamentes

In sequent es presentat li provisori Regulamentes del Comité
linguistic (CELIA) e del Academie, elaborat del comission preparatori.

Occidental-Union +
Central Oficie

Karl Janotta +
Secretario

Hans Hoerbiger +
Provisori Presidente

Engelbert Pigal +
Director

=== COMITÉ LINGUISTIC

==== Regulament

// XXX TODO -- liste:

// XXX NOTE -- li marca original de págine -8- esset in listune 4:

// XXX NOTE -- li marca original de págine -9- esset in listune 17:

1. Comité Linguistic del Occidental-Union, nominat secun li autorisat
   Statute «Comité Explorativ de Lingue International Auxiliari»
   (abreviat: CELIA) es un comission international e public, instituet
   del Occidental-Union secun su Statute.

2. Li programma del Comité es explorar propositiones pri li grammatica
   e glossarium del lingue international Occidental, e preparar li
   decisiones del Occidental-Academie.

3. Li decisiones del Comité pri linguistic questiones es a considerar
   quam expressiones de opinion e lor oficialisation es fat per li
   Occidental-Academie. Til ti oficialisation li nov formes posse
   esser usat in textus de instruction solmen con un asterisc (*).
   quel indica que ti formes es solmen in experimentation, ma ne ja
   aprobat.

4. Un parte del membres del Comité (10 til 30) es electet per li
   Senate del Occidental-Union secun li proposes del Central Oficie.
+
Un admaxim egal númere de membres posse esser cooptat per li Comité.
Li candidatura de membres cooptand deve esser proposit e suficentmen
motivat per adminim du membres e li acceptation fat sive per votation
inter li membres sive per unanim decision del Direction del Comité. In
plu omni membres del Occidental-Academie sin exception es anc membres
del Comité.

5. Li Comité ne es obligat, acceptar o conservar membres queles ne usa
   li lingue oficial Occidental.

6. Un membre quel evidentmen refusa subordinar se al resolutiones del
   Comité, o quel durant un demí annu, sin motive valid, ne ha
   participat in li labores del Comité, cessa automaticmen esser
   membre, pri quo il deve esser informat per li Direction del Comité.

7. Li Direction del Comité consiste ex un Presidente, un Secretario,
   un Redactor e li Director del Central Oficie del Occidental-Union.

8. Li Direction es electet per li membres del Comité, por un periode
   de du annus per votation, ma it electe self su functionarios.

9. Li Direction have li jure cooptar se extraordinari membres por
   division del labor, e ordinari in casu de abdication de un de su
   functionarios.

10. Omni hom posse far al Comité propositiones linguistic, redactet in
    li oficial lingue. Ma li Comité ne es obligat posir un proposition
    in discussion, si it ne es conform al Regulament e decisiones del
    Comité e si ne adminim un membre del Comité recomanda it.

11. Omni membre have li jure inserter notas in li oficial circulares
    del Comité, por publicar talmen su opinion, si li material medies
    del Comité permisse ti publication.

12. Omni membre have li jure misser al Direction del Comité articules
    linguistic o organisatori in tam mult exemplares que ili posse
    esser dismisset del Direction al céteri membres del Comité. Tal
    scrites recive un current numeró quam circulare del Comité, si ili
    es arangeat in li form customat del céteri circulares del Comité.

13. Omni final propositiones e decisiones deve esser publicat in li
    circulares con indication del nómine del votantes por e contra.

15. In li corespondentie con li Comité chascun question deve esser
    tractat sur separat folie, scrit sur un látere, con un márgine in
    levul de adminim 20 mm, e deve portar li date, signatura e adresse
    del propositor. Li formate deve esser 210 x 297 mm. Li manuscrite
    deve esser facil leibil, preferibilmen scrit per machine, con
    lineas interspaciat.

16. Omni propositiones pri mutation o innovation del lingue del Comité
    deve esser acompaniat de un detalliat indication
+
--
[loweralpha]

.. pro quo li existent form o metode es minu apt.

.. pro quo li proposit nov form o  metode vell esser plu apt.

.. quel formes del derivation es evocat per li mutation e

.. quel expedientes es necessi por evitar possibil colisiones o
   complicationes pro altri formes o regules ja existent.

--
17. Li Presidente decide pri submisser a votation un question quel
ha esset suficentmen discusset. Ti decision deve esser anunciat in un
oficial circulare tri mensus in ante per un nota redactet quam seque:
«Li responses del membres pri li question de ... deve esser misset al
Comité ante li ...» Li date es fixat del Presidente.

18. Chascun membre de quel li response ne veni al Secretaria in ti
intervalle, es considerat quam «índiferent» pri li questiones posit.

19. Li questiones proposit al votation deve esser enunciat talmen, que
li membres posse responder simplicmen per «yes» o «no» o «
índiferent».

20. Omni membre have li jure demandar un nov discussion e votation pri
questiones ja decidet. Ma li Comité deve votar, esque it accepta un
nov discussion.

21. Pri special paroles de scientie, tecnica, arte etc. li Comité
decide ne ante audir competent specialistes.

22. In votationes decide li absolut majorité (it es plu quam 1/2 del
númere de membres) del Comité, ne solmen del votantes. In fundamental
trates changeant tot series de formation de paroles es necessi un 2/3
majorité del tot Comité.

23. Li Comité covri su expenses in general
+
--
[loweralpha]

.. per voluntari subventiones, queles deve esser quittat in li
   circulares del Comité,

.. per abonnamentes al circulares per non-membres (contra anticipat
   payament de un summa fixat per li Redactor), o si (a) e (b) ne
   sufice:

.. per li Central Oficie secun decision del Senate.

--

24. Divergenties de opiniones relatent li regulament o decisiones del
    Comité es arbitrat del Comité self per li absolut majorité del
    membres.

25. Mutationes del regulament deve esser aprobat per li absolut
    majorité del Comité e per li Senate del Occidental-Union.

26. Propositiones pri li self-dissolution del Comité deve esser signal
    per 1/3 del membres e aprobat per 2/3 del votantes.

27. In li casu de dissolution del Comité su eventual possessiones
    apartene al Occidental-Union.

// XXX NOTE -- Ci esset ti separator: -----

// Occidental-Academie {{{2
=== Occidental-Academie

==== Regulament

// XXX NOTE -- li marca original de págine -10- esset ante listune 3:

// XXX NOTE -- li marca original de págine -11- esset in listune 13:

// XXX FIXME -- Un signe de libre es usat in listun 9:

1. Li Occidental-Academie es un comission instituet del
   Occidental-Union secun su Statute.

2. Li programma del Academie es
+
--

[loweralpha]

.. decider pri li final ratification del decisiones del «Comité
   Linguistic» del Occidental-Union por lor aprobation in universal
   usada.

.. dar linguistic consilies e aprobationes por dictionariums, manuales
   e altri medies por aprension e aplication de Occidental.

.. dar certificates por docentes de Occidental.

.. validar certificates de aprension.

.. representar li Occidental-Union in linguistic questiones.

--

3. Li Academie consiste ex li autor de Occidental quam membre honorari
   e ex admaxim 15 membres ordinari. In ultra li Academie posse
   cooptar un til six universitari professores de linguistica o
   litteratura quam extraordinari membres con li titul Protectores, un
   de ili anc con li titul Presidente honorari. Pri li election e
   cooption de su membres li Academie self decide in consense con li
   Central Oficie del Occidental-Union e secun propositiones fat sive
   del Comité Linguistic, sive del Protectores, sive del Senate del
   Union.

4. Chascun membre, quel evidentmen refusa subordinar se al
   resolutiones del Academie, cessa automaticmen esser membre, pri quo
   il deve esser informat per li direction del Academie.

5. Chascun membre ordinari, quel durant un demí annu, sin motive
   valid, ne ha participat in li labores del Academie, cessa
   automaticmen esser membre, pri quo il deve esser informat per li
   Direction del Academie.

6. Li Direction del Academie consiste ex un Presidente, un Secretario
   e tam mult altri membres quam li Academie judica quam necessi.

7. Omni decision del Academie deve esser insertet in li oficial revúe
   del Occidental-Union, ma sin indication del númere e del nómines
   del votantes. Ti ci dates es comunicat solmen al membres del
   Academie.

8. Per li simplic ratification (nominat «admission») de un nov form o
   regul per li Academie, li corespondent form o regul valid til tande
   ne es oficialmen abolit. Li abolition deve esser expressivmen
   decidet; ma mem in ti casu li form o regul valid til tande es
   oficialmen tolerat ancor durant un periode de transition de quar
   (4) annus.

9. In li grammaticas e vocabulariums editet o aprobat per li
   Occidental-Academie deve esser aplicat li sequent signes:
+
--

- † (cruce) por obsolet o abolit formes, con li eventual indication
  del periode de transition.

- * (asterisc) por nov formes ancor ne admisset del Academie.

- □ (i.e. un libre) por términos special, queles es tolerat por
  usation in li scientic o tecnic litteratura; ti ultim signe posse
  esser remplazzat per altri signes indicant li special scientie e
  tecnica.

--

10. Por li revision e aprobation de alquel ovre grammatical etc. li
    editor deve payar un taxe de 2/100 del complet edition, ma adminim
    10 exemplares.

11. Qui vole reciver un certificat quam docente de Occidental, deve
    far un exámine córam du membres ordinari del Academie secun li
    regulament de exámines por docentes, stipulat del Academie, e
    payar in ante un taxe de 2 dollares al Academie. Li certificate
    have un validitá de 10 annus.

12. Omni Occidental-docente junt con un altri Occidental-docente have
    li jure dar a altri persones un certificate de aprension de
    Occidental secun li regulament de exámines de aprension, stipulat
    del Academie. Por li validation del certificate chascun candidate
    deve payar in ante un taxe de 1 dollar al Academie. Li certificate
    have un validitá de 10 annus.

13. In votationes decide li absolut majorité (it es plu quam 1/2 del
    votantes; in electiones decide in li unesim votation li absolut
    majorité del votantes, in un eventual duesim votation li relativ
    majorité.

14. Omni scrites e publicationes oficial del Academie deve haver li
    signatura del presidente e del secretario del Academie, e li
    signatura del director del Occidental-Union, o de lor vicarios
    respectiv. Omni certificate de un Occidental-docente deve haver in
    ultra li signatura del du membres del Academie, queles ha examinat
    li candidate.

15. Li Academie covri su expenses in general per
+
--

[loweralpha]

.. voluntari subventiones, queles deve esser quittat in li oficial
   organ del Occidental-Union.

.. taxas por aprobationes e certificates.

.. subsidies del Occidental-Union.

--

16. Divergenties de opiniones relatent li regulament o decisiones del
    Academie es arbitrat del Academie self por li absolut majorité del
    votantes.

17. Mutationes del regulament deve esser aprobat per li absolut
    majorité del membres del Academie e per li Senate del
    Occidental-Union.

18. Propositiones pri li self-dissolution del Academie deve esser
    signat per 1/3 del membres e aprobat per 2/3 del votantes.

19. In li casu de dissolution del Academie su eventual possessiones
    apartene al Occidental-Union.

// Interlinguistic reminiscenties {{{2
=== Interlinguistic reminiscenties

_De E. de Wahl._

:pednote1855: Li parte I ha aparit in li nr 41 de Cosmoglotta, quel \
regretabilmen ja es exhaustet. Ma in su témpore noi ha fat printes \
special del unesim parte, quel nov abonnates posse reciver contra ö S. \­
0.50. Red.

==== II{blank}footnote:[{pednote1855}]

Li vive rula, li unes abandona li scene, altres apari, nov homes, nov
problemas, nov labores. Ili ha submerset presc omnicos in li Lethe del
oblivie. Lu poc quo restat in mi memorie e singul documentes yo prova
fixar ci, forsan tre disparat e íncoherent, sovente retornant a
anteriori témpores o ja anticipante posteriori evenimentes.

// XXX NOTE -- li marca original de págine -12- esset in li sequent
// paragraf:

Li unesim trist eveniment esset li discordantie con Zamenhof, evocat
per mi forsan tro juvenil ímpetu in postulation de changes. Ili esset,
quam on posse vider hodie in Occidental, in un direction quel aproxima
li L.I. al comun europan formes e subordination al leges trovat per li
linguescientie, elimination
del ínnatural accentu, del arbitrari finales -o, -a, -e, -as, -is, -os
etc. Pri ti periode yo, quam ja dit supra, presc ne possede
documentes, e anc mi memorie ne ha conservat li detallies. Ma forsan
un die on va trovar ti corespondentie in li secret archives de
Esperanto, quande ili va esser apertet al historic exploration e
publicat. Ma yo possede un lettre de sr Trompeter, li editor e mecen
de «La Esperantisto», li caractere de quel es sat conosset per li
publicates in li Esperanto-presse, e quel forsan va interessar li
letor. In ti lettre del 28 septembre 1891 Trompeter scri:

____
Kiam mi legis la artikolon de doktoro Zamenhof en numero 7 de
«Esperantisto», mi pensis, se mi loĝus kun Zamenhof sub sama
tegmento, kaj mi vidus la manuskripton antaŭ la presado, mi dirus:
«Amata sinjoro, elektu alian tonon, memoru, Vi enprenis la proponojn de
sinjoro de Wahl kaj de aliaj en la publika gazeto sen komentaro, kaj
nun Vi ne havas la rajton, respondi en tiel morda tono. Diru, kion Vi
volas diri kontraŭ la proponoj, sed ne tiel tranĉante!» Tiam mi
forgesis duone la afero{blank}footnote:[Ples remarcar li erra contra
li acusative.]
ĝis Via letero memoris{blank}footnote:[Vell dever esser: memorigis.]
min al ĝi...
(Nu seque un exposition del desfacil financial etc situation de
Zamenhof) ... Tiel sidis Zamenhof nun eble en ne tenebla
situatio{blank}footnote:[Ples atenter ti form.],
kaj lia ĉagreno kondukis lian skribilon...

Estus damaĝe por la afero, se restus la nuna malagordo inter Vi
ambaŭ, Ĉu Vi, estimegata Sinjoro, konsentas, ke mi pro Via afero kun
Zamenhof skribu al li? Ĉu estas eble, fari pacon inter Vi kaj li?
Kiel?
____

Nu, li pace esset fat, ma li amical sentimentes de antey hat cedet a
plu oficial corect relationes, queles pos quelc témpor cessat
completmen, pos que yo hat completmen abandonat li Esperanto-movement
in april, may 1894.

Hodie, quande yo have plu quam sixant annus, yo comprende Zamenhof e
regreta que il ne vive plu por posser presser le li manu.

Il esset mi grand mastro e instructor, e quáncam it posse semblar que
yo es su max fanatic adversario, yo self estima me quam su max fidel
successor, ne in li líttere ma in li mente.

// XXX NOTE -- Ci esset li marca original de págine -13-

(Image de Julius Lott)

// XXX TODO -- Image.

Nascet in Fürstenfeld (Austria), 16. 2. 1848.

Morit in Wien, 21. 2. 1905.

// XXX NOTE -- Ci esset li marca original de págine -14-

Inter li du extremes, li aprioristes e li pur naturalistes, Zamenhof
esset ti quel volet unir ambi postulationes, li naturalitá e ínmediat
comprensibilitá con absolut regularitá. Por ti remot témpores, por li
yunesse del autor, por su ínsuficent filologic conossenties, su ovre
esset un fenomen li signification de quel nequande va esser obliviat.

Just ti mental fundament de Zamenhof quel hat impressionat mi yun
mente, esset li bussol quel guidat me durant mi explorationes in li
virginal foreste del natural lingues. Unir li naturalitá,
internationalitá e regularitá, in ti aspiration yo senti me plenmen
disciplo de Zamenhof. Ne in li form, ma in li spíritu de su genial
ovre.

«On recompensa mal li mastro, si on resta sempre disciplo» ha dit
Nietzche.

==== III

Quam ja dit supra, ja durant mi esperantistic periode yo ne solmen
ocupat me pri reformes in Esperanto ma anc li movement de
novicreationes de international lingues interessat me e yo examinat li
projectes queles yo posset reciver: Liptay, Kosmos (Lauda), Communia
(Stempfl), Universala (Heintzeler), Novilatin (Beermann), Lingua komun
(Kürschner), Nov Latin (Rosa) e specialmen Mundolingue de Lott e Idiom
Neutral de Rosenberger.

Ja in 1888 Lott hat publicat un brochura «Ist Volapük die beste und
einfachste Lösung des Weltspracheproblems» e in 1889 «Eine
Compromiss-Sprache als beste und einfachste Lösung des
Weltsprache-Problems». Il quasi predessinat li general form del futur
L.I., constructet ex elementes del international paroles. Ti brochura
contenet un curt grammatica e un parte del vocabularium (li líttere A)
por demonstrar su principies.

In li grammatica advere regnat ancor suficent artificialitá. p.ex.
_mies_ (noi), _tues_ (vu), _soster_ (lor, de illos), _saster_ (lor, de illas),
_so_ (il), _sa_ (illa), _va_ (quo), _ve_ (qui), _vopro_ (pro quo), _desh_ (deci),
_okgessib_ (87) etc.

Ma Lott ja conserva li 3 finales, «a», «e», «i» in li verbes in li
infinitive, advere ne in li conjugation.

// XXX NOTE -- li marca original de págine -15- esset in li sequent
// paragraf:

Ja in 1890 yo coresponde con il pri divers formes de su grammatica,
lexico, e li derivation. Il scri li 29. 8. 1890 de
Vienna in lingue german: «Yo ha provat adaptar Vor sistema de
derivation al lingue international por junter it al lexico. Si it nu
ea suficent bon che li sufixes, it falli totalmen che li prefixes.
Ples haver li bonitá misser me li derivation in Vor sense solmen in
lingue international, ma possibilmen bentost». Il anc proposit me
prender sur me li redaction de un periodic quel il volet editer, ma ti
cose naufrageat, e ne ante 1893 Lott atinget editer li revúe «Le
Kosmopolit» in L.I. e german, ma sub propri redaction. Su brochura e
li circulares hectografat dismisset a omni conosset adresse támen
visibilmen ne hat atraet li interesse in suficent gradu.

In omni casu li missuccess descorageat Lott talmen que in 1891 secun
su lettres il volet jettar omnicos. Ma tande li libre de Liptay, quel
expresset idés simil al sui e hat evocat interesse in li publica,
pussa le denov al labor. Il edite in august 1891 un «Suplent folie»
in lingues angles, german, frances, italian, hispan e adjuntion in su
propri lingue. Inter altricos il publica pri li pronómines anc li
propositiones de me, Runstedt, F.V. Lorenz e Liptay. It es
interessant, que omni quar trovat necessi special formes del casu
índirect. Támen Lott conserva su proposition con un sol form por omni
casus. Anc li formes so, sa, soi, sostre etc resta. Ma li mutual
corespondentie inter li progressiv interlinguistes visibilmen hat
influentiat le, e quande in fin de 1892 il comensa li edition de su
revúe «Le Kosmopolit» in li cap ja sta inter li fundamental regules
li pronómines: mi, tu, elo, ela, ele; noi, voi, elos, elas; e mie,
tue, sue, nostre, vostre, lostre. Ti ultim form il anc ne ha abandonat
in su edition 1899. Su revúe, editet in mundolingue e german, támen ne
posset perdurar 2 annus. Advere in decembre 1894 Lott scri, que il
vole provar recomensar li edition, ma to nequande esset
fat.{blank}footnote:[Couturat in su Historie de la Langue Universelle
di que ha aparit solmen 3 numerós del Kosmopolit (1 dec. 1892 til 1
febr. 1893). To es un erra. Yo self possede li numerós til 1 april
1894 (nr. 13).]

Talmen ti edition provant junter omni progressiv mundlinguistes in
constructiv comun labor ne posset tener se, sammen quam li unesim tal
revúe «Interpretor», editet in Leipzig de Karl Lentze in annu 1889
til 1890, quáncam li base del lingue de Lentze esset tot altri quam ti
de Lott. Il volet ye exemple
de Volapük constructer un L.I. sur un simplificat e foneticmen
transscrit Anglés, un metode quel til nu ne havet success, e ne posset
entusiasmar mult persones. In li revúe «Interpretor» ti direction
esset subtenet per Knuth, e li finnlandés Ilmari Krohn, chascun
naturalmen con su propri personal nota. Ma anc bon e rasonabil
articules esset publicat in ti unesim revúe, p.ex. li considerationes
de Dr. Fricke, Lott e altris, ma Lentze e Krohn restat ínflexibil e
pos li fine del Interpretor on ne audit plu pri ti direction til que
Dr. Fr. Riedel e O. Scheffers publicat un articul in «Uniti langue»
(Kosmoglott 1923 nr 1 [13]). In li sam numeró on trova anc specimenes
del lingue de Lentze e de A. Nilson.

It esset do un general discadentie in li interlinguistic movement.
Volapük plu e plu dissoluet se e su anteriori adherentes serchat un
solution in li max divers directiones (chascun annu aparit un serie de
nov projectes, ma omni sin minimal success, ni nov usabil idé).
Esperanto luctat pro su vive e existentie, e sin li tenacie de
Zamenhof, su marita e quelc de su adherentes, anc ti movement vell har
ruit.

Li movement progressiv do desaparit del publicitá in li privat
corespondentie del singul ductores e interessates.

Sub li influentie de mi considerationes e forsan anc del altri
naturalistes, quam Grabowski etc, Lott plu e plu conforma su
conceptiones con li nostris e finalmen transi al plu historic
scrition, quáncam to sembla le esser solmen un transitori statu e que
li futur evolution va esser un totalmen fonetic ortografie, o plu rect
vell esser un grafic fonetic, nam il vole pronunciar li «t» in li sufix
«-tion» quam pur «t».

Yo auxiliat le per critica de su sempre renovat propositiones
hectografat e per composition de un parte del vocabularium por su
necessitás (li líttere H). Talmen li final form de su lingue ja es tre
simil al hodial Occidental.

// XXX NOTE -- li marca original de págine -17- esset in li sequent
// paragraf:

Yo possede un hectografat folie circulari de Lott con suficent vast
propositiones grammatical e con mi contra-propositiones fat per rubi
incre. E hodie yo deve confesser que mult formes de Lott, queles yo
tande rejettat, sub influentie del lingue hispan, esset plu bon. E
quáncam noi ne posset acordar nor idés totalmen, on posse vider in su
ultim edition in 1899, quel il preparat por li Exposition
International in Paris, un remarcabil modernitá, p.ex. li duplic valor
de «c», li duplic consonantes
etc; ma il conservat li italian pronunciation «k» del combination «ch».

Ti evolution Lott visibilmen atinget per li augmentation del general
interesse pri linguistic questiones, quel ductet al aparition del
revúe «Linguist» sub redaction de Max Wahren in Hannover, in annu
1895 e 1897. Ti periode es suficent detalliat tractat in li «Histoire»
de prof. Couturat. On save que un positiv resultate per ti
discussiones ne ha esset atinget, e pro to Lott denove fat grand
eforties por crear un international societé por presentar un modern
usabil L.I. Il dimisset hectografat circulares con propositiones por
un detalliat grammatica, corespondet con divers mundlinguistes, scrit
articules e circulares e monstrat un vermen admirabil activitá,
energie e persistentie, specialmen quam ja dit ante li Exposition
International in Paris 1900. In 1899 do apari un nov ovre (li quasi
final de Lott) «Un lingue international pro le cultivat nations de
tot mund» con «Gramatic, Dialogs, letters et vocabular. Composit in
anglian, frances, german, italian et universal lingue, pro le practic
application durant le exposition universal de Paris 1900, Imprimeria
Carl Fromme, Vienna.»{blank}footnote:[Secun un recent comunication de
ti printería-editoría li libre es totalmen exhaustet. (Red.)]
In li «Histoire» de Couturat es recenset e exposit solmen ti ultim
fase de evolution de Lott. Pro to it vell esser forsan interessant
comparar su unesim provas, proque li libres e editiones de Lott nu es
desfacilmen recivibil.

Ci do seque quelc specimenes ex su ovres. Li unesim esquisse (1889)
regretabilmen ne contenet provas del lingue, pro to yo va restricter
me ye exemples de 1891, 1893 e 1899.

.1891 
____

Un universal lingue solu tand ave le esperanze de un bon
resultat, quand le studie de id ese util pro omno. Anke le latin
kontentaria le kondizion, ma ne in tel mod, quam un modern nov
dialekt. Le latinik lingue ne satisfa le necesités de mondokomercie.
Ni sue iregular gramatik ni sue inkomplet vokabular esse utilabl si
esenzial modifikazions. Mult vokabls ese kognit solu (a) le
latinistes.

____

.1893 
____

Ele esse un fakt, qe l italianik, frankogallik ... lingue se
formé ex le latin in un temp (intr e pos le migration del poples) qui
ne estimé le sciences ni le kultur, et le derivation de
un nove regular latinik dialekt esse possibil anke
nos{blank}footnote:[Ci on ja vide, que il adopte li casu objectiv por
li pronómines personal.] si noi vole.

____

.1899 
____

In brevi tempor esseré cognit et usat ist lingue in tot le
mund et ele obteneré un perfection qua neun lingue del terre. Ingenios
dames ha un grand influence, ergo ha Vo le bonitá intrar in le
mundolingual societá.{blank}footnote:[Ci ja es usat li líttere c con
su duplic pronunciation. On mey anc remarcar li metode formar li
imperative _ha Vo_ per inversion del pronómine. Ci Lott anc usa _Vo_,
durant que in su unesim conceptes il usat _Tu_.]

____

Li letor va constatar que li evolution de Lott ha movet se plu e plu
in li direction quel yo sempre sublineat.

In ti ultim ovre de Lott on ja posse vider li fundament de omni
naturalistic provas. Ma un clar formulat derivation manca anc ci. Pro
to in ti témpores su demarchas fallit totalmen. Li publica ne
comprendet li valore etern de su labores, li justitá de su idés e li
clar videntie de ti profetic mente.

Un prematurat morte ha sepultet li fructes de su vast planes.

Tam plu noi deve ci memorar que Lott esset li unesim modern
mundlinguist. Nietzsche ha dit: «Primnascetes es sempre sacrificat».
Ma lor glorie resta.

// XXX NOTE -- Ci esset ti separator: -----

// Corespondentie {{{2
=== Corespondentie

____

Heinrich Lott

a senior Karl Janotta, presidente del societé «Cosmoglotta» in Wien.

Plur vezes yo havet li honore esser invitat de vor estimatissim
societé a discurses, e in un tel ocasion li desir esset expresset,
reciver plu detalliat informationes pri Julius Lott, quel plur annus
ante nu anc prendet parte activ al elaboration de un lingue
international. Julius Lott esset li fratre de mi patre, e yo es parat
con plesur dar informationes pri li vive de mi oncle.

// XXX NOTE -- li marca original de págine -19- esset in li sequent
// paragraf:

Mi oncle Julius nascet ye li 16 februar 1848 in Fürstenfeld in Styria.
Li die de su morte es li 21 februar 1905, do il morit in li 58-m annu
de su vive quam oficiario superior in li direction del Privilegiat
Austrian Nordferrovia in Wien. Mi avo, i.e. li patre de Julius Lott,
Friedrich Lott, originat de Halberstadt in li provincia Saxonia e
nascet ta 1794 quam filio del borgesi stoffero Friedrich Lott in li
dom «Hinter der Münze» (detra li monetería), quam di li testimonie
baptismal de mi avo. Il immigrat versimil inter 1820 e 1830 a
Austria e etablisset se in Fürstenfeld in Styria u il maritat li filia
Franziska del interprendero de edificies Andreas Flack. De ti maritage
provenit 16 filies, de queles li max mult morit in un etá tre juvenil.
Un etá medial atinget solmen li filio Heinrich Lott (mi patre), un
filia Maria Lott maritat Pferschy (de quel vive ancor un nepotessa, li
instructressa Martha Pferschy, in Pischelsdorf in Styria) e Julius
Lott, de quel vive ancor li filias Ernestine, vidua de Calben e
remaritat Günther, e Sidonie Lott, ambi in Wien.

Li patre de Julius Lott esset dom-proprietario e lupul-negociant in
Fürstenfeld; li dom patrin jace vis a vis li «Grazer Tor» (Porta de
Graz) e es hotémpore proprietá del casse de sparniages de Fürstenfeld.
Por Julius Lott li carriera militari esset selectet. Il esset misset
al Academie Militari in Wr. Neustadt, quel il quittat in 1866 quam
leutenante de artillerie por participar strax li campanie contra
Prussia. Ma pro que in li prussian armé versimil proxim consanguines
marchat contra Austria, Julius Lott petitionat pro to, quam on di, e
poy li ordone de march-rut ha esset changeat. Ma Julius Lott plu tard
trovat ne plu joy de su carriera militari, nam il quittat voluntari li
servicie militari e intrat li servicie civil del Privilegiat Austrian
Nordferrovia. Il maritat se con Ernestine Paulizza, li filia de un
architecte e ingeniero de Graz.

// XXX TODO -- "mi tante -- ella" ?

In mi infantie yo passat tre sovent li témpore del vacantie scolari in
li familie de mi oncle Julius Lott e de ti témpore it restat in mi
memorie, que li oncle mastrisat tre mult lingues, e il trublat
alquande mi vacantial repose per que il instructet me zelosimen in li
lingue italian, nam il opinet que li hom deve posseder lingues por
trovar su existentie in li munde. In annus posterior yo observat que
li oncle ocupat se tre zelosimen pri li lingue international «Volapük».
Sur su scritable un grand quantité de libres e brochuras stat
staplat. Yo opine que il editet anc un revúe e fat un corespondentie
de un enorm extension: nam yo memora ancor, que yo portat con su
filies li lettres in corbes al posta. Til tard in li nocte il sedet
apu su scritable, talmen que mi tante devenit tre indignat pro to;
ella maledit to e dit sovente, que ella va metter li tot linguallia
(_Sprachenkram_) in li forn, si il ja ne plu have témpore por su
familie. Sovente li oncle fat in Wien in divers salas discurses a
queles anc yo devet assister, e che queles sempre mult auditores esset
reunit. Yo audit tre sovente, que il volet mem ameliorar li lingue
international «Volapük», e il anc editet divers libres in ti sense.
Teles es ancor trovabil, quam on di, in li biblioteca del universitá
in Wien.

Regretabilmen li familie ne respectat li corespondentie de mi oncle,
quel il havet in grand extension con interessates in li exterland. Li
filies de Julius Lott esset in li ultim annus de su vive ne plu in li
hem patrinal. Yo self esset ja in Germania, e su marita, mi tante,
tractat li libres e scriptes quam maculatura, talmen que regretabilmen
mem ne un document nos es conservat pos li morte de mi oncle. Yo posse
ancor memorar har sovente videt, que un vivi corespondentie evenit con
un senior de Wahl.

// XXX NOTE -- li marca original de págine -20- esset in li sequent
// paragraf:

Si vor estimatissim societé nu ha constatat, que ja Julius Lott havet
idés fundamental por un lingue international secun vor sistema,
e si sur fundamentes posse esser continuat li construction, e si per
to Julius Lott posse esser honorat denove, to es un joy e satisfation
por su descendentes, e noi regreta extremmen que noi ne posse
contribuer ancor plu precis detallies ex li vive de Julius Lott. Si
noi vell posser decovrir alcú quelccos, quo vell posser esser de
interesse por vos, noi va hastar informar vos pri to. Pro mi ciecitá
(causat per un grav oftalmie) regretabilmen yo self ne posse dedicar
me in detallie al studie de vor lingue international, ma mi filio
Eberhardt Lott, quel ja ha visitat anc vor discurses, have un grand
interesse pri it, precipue pro que il es studiante in li Academie por
Comercie International u il ocupa se anc pri li studie del francesi e
anglesi lingue, e pro que il ultra to es inscrit por latin in li
universitá de ci.

Respectosimen +
Heinrich Lott, +
Wien XVIII., Erndtgasse Nr. 31.

____

// XXX NOTE -- Ci esset ti separator: *

Li autor del superiori epistul, Heinrich Lott (li filio del fratre
Heinrich de Julius Lott), ha esset durant long annus li comercial
director de societés anonim in Germania. Il devenit ciec pro un grav
oftalmie, quittat pro to li servicie quam director comercial e ha
depoy in Wien un firma special e in gross por musical cordes e por
cordes de ráckets. Senior Heinrich Lott nos ha mettet in disposition
anc un fotogramma de su oncle quel noi reproducte in ti ci numeró. Ti
qui vole informar se adplu pri li cosmoglottic activitá de Julius
Lott, ples leer anc li Interlinguistic reminiscenties de sr E. de Wahl
in li present caderne e li articul «Un precursor ínjustmen obliviat»
de Prof. Ric. Berger in nr 57.

_Red._

// XXX NOTE -- Ci esset ti separator: -----

// Litteratura {{{2
=== Litteratura

// Pro quo noi studia historie? {{{3
==== Pro quo noi studia historie?

_De John Lee Madox._

// XXX NOTE -- li marca original de págine -21- esset in li sequent
// paragraf:

Li studia del historie procura nos li perspective necessi por
comprender nor epoca e posi nos in statu separar li durativ elementes
in li vive contemporan del accidental e fugitiv tales. Studiante
historie, noi es (quam Morley dit) simil al avio quel vola tam alt,
que il vide un gruppe de insules ne quam li isolat partes de terre,
quam ili sembla visibil del superficie del mar, ma quam parte de un
unic catene de montes submerset. Comparante li presentie con li
passate, noi vide strax que li presentie es superior in respect
material, spiritual e moralic. Sclaveríe e servitude ha desaparit.
Soldates, marineros
e scol-infantes ne plu es bastonat. Li potentie fisical e legal del
mann súper li fémina diminue. Paratitá a auxilie e a misericordie es
crescent. Qualmen noi posse venir a comprender ti ci circumstanties
ameliorat? Solmen per li studia del passate, quel ha productet les.

Li historie ne repeti se total exactmen, pro que li factores ne es
precismen li sam e pro to li analogie ne sempre es plen perfect. Ma un
diligent studie del capitules de historie revela un lege del
continuitá, un lege del permanentie per li change, un lege del mutual
dependentie inter omni membres del rasse homan e un lege del progress
moralic.

Un studie critical del historie es higienic por li intelectu, pro que
ti ci es liberat de su credulitá. Li credul homes credet que li grand
guerre va esser un «guerre por far fine a omni guerres futuri»; ma
qui conosset li historie universal, ti facilmen posset previder li
querelle pri division del terren conquestat quel vell erupter che li
conclusion de pace.

Li studia del historie fa plu vast nor horizonte mental. Un hom qui in
su pensas nequande transgresset li límites del territorias de su
patria, necessimen es un hom con mentalitá limitat. Su circumité apare
le plu important quam omni altricos; li turre de eclesia de su village
es plu alt quam li egiptian piramides. Ma si il es in statu vider
qualmen altri homes vive, il deveni un altri hom. Il veni a conosser
homes e coses pri queles il nequande havet un idé. Si il es un
observator sincer e atentiv, il va remarcar que quelc homes e coses es
plu bon e quelc plu mal, e que ultra li montes de su patria existe
mani bon coses. Quo noi in viages aprende pri altri landes, to li
studie del historie doce nos pri altri eras.

Li studie del historie fa nos plu tolerant. Quande noi aprende que in
passat témpores honest homes ha luctat pri principies queles hodie noi
reconosse quam índigni, que homes religiós ha sequet con ardore a un
doctrina quel li homes de plu tard epocas ha reconosset quam fals, que
sincer homes in bon credentie ha fat actiones queles hodie chascun hom
regarda quam ínjust, tande noi va hesitar dogmatisar o insister pri
que nor judicies es ínfallibil e que chascun que ni concarda con nor
opiniones, es sive un foll sive un rascale.

_Ex "Current History", New York. +
Trad. A. Deminger._

// XXX NOTE -- Ci esset ti separator: -----

// XXX NOTE -- Ci esset li marca original de págine -22-

// Foren lingue {{{2
=== Foren lingue

Un mann qui ne savet alcun parol turc, havet comercial aferes in
Turcia. Un die il venit ínprevidetmen in un restaurante completmen
turc. Perplex il regardat li curiosi grafic signes sur li menú-cart,
quel li servero turc presentat le. Con rapid decision il indicat per
li fingre li unesim linea; e li servitor aportat le un pilav, un
manjage de ris. Li gast esset content, e quande il permanjat li ris,
il indicat li sequent manjage. Li servitor aportat denove un pilav,
quel esset preparat in altri maniere. Solmen con pena li gast inglotit
su iritation e li duesim pilav. Quo il devet far nu? Demandar li
sequent manjage? Forsan it esset denove un pilav. Il decidet pro to
observar, quo li mann ye li table vicin vell dir al servitor, e si li
manjage vell pleser le, imitar li parol tam bon quam it successa. Li
farinage por exemple, quel li vicino ho-moment manjat, aparet
passabilmen gustosi. Bentost poy li mann vocat li servero, monstrat a
su platil e dit: «Dahar bir defa». Quande li servitor aportat ancor
un portion del apetitosi farinage, li gast fat signe al servero,
monstrat a su platil e dit: «Dahar bir defa». Li servitor aportat --
ancor un portion pilav. Plu tard al foren dit su amic comercial, que «
Dahar bir defa» significa «Lu sam!»

Ex li revúe mensual «In die weite Welt», Wien, II-m annu, nr. 5, may
1925.

_Translatet de Karl Janotta._

// XXX NOTE -- Ci esset ti separator: -----

// Fabul {{{2
=== Fabul

_De Klabund._

Per mi promenada-baston yo per-picat un formiciera. Furiosimen e
alarmat li animales curret in turbulentie. Subitmen yo levat li baston
e partit. Li animales, vidente desaparir li baston in li aer, criat: «
Quel strangi avie!» -- Un formíca apartmen audaciós, ha ascendet li
baston. Yo devet escartar it. Totalmen iritat ella arivat che li
altres. Excitatmen ella exclamat: «Li avie tenet un hom in su
ungules; it manja homes!» -- Poy ella retirat in contemplation, scrit
un libre: «Specie, descendentie e organisme del nov decovrit
baston-avie» e ella esset habilitat a professor ordinari del zoologie
in li universitate de Przmnldtbk...   Trad. E.P.

// XXX NOTE -- Ci esset ti separator: -----

// XXX NOTE -- Ci esset li marca original de págine -23-

// Record de rapiditá {{{2
=== Record de rapiditá

In li munde animal. Quam ha monstrat minuciosi explorationes de un
anglés scientist, li special atention de quel es directet al mecanisme
volativ de divers species de insectes, on posse considerar quam li max
rapid ente in li munde un mosca in Sud-America, nominat Cephonemyia.
Ti micri artist in vol atinge li íncredibil rapiditá de 350 metres ye
seconde. To es 1260 kilometres per hor, do presc lu triplic del actual
record de rapiditá che li modern aeroplane (460 km/h). Ultra to li vol
es absolut ínaudibil por li orel homan, e anc li ocul posse percepter
solmen un punctu passant con fabulatri rapiditá.   Trad. EW.

Do li mirabil mosca Cephonemyia have un plu grand rapiditá quam li son
in aer (331 m/sec ye 0°C e 760 mm Hg pression atmosferic) e presc li
rapiditá de un punctu equatorial del terre (463 m/sec) e quam li
molecules de aer atmosferic (485 m/sec ye 0°C).

In li cosmo. Li american astronomos Humason e Pease mesurat li max
grand rapiditás de materie, i.e. de córpores celestic. Secun li
pricipie de Doppler aplicat al spectroscop ili recentmen constatat que
quelc nebules in li constellation Coma Berenices have un translation
in li radie visori (velocitá radial) de 7800 km per seconde. Abstraet
del lúmine (299 800 km/sec) e altri oscillationes del ínmaterial «
ether» (radies gamma, Röntgen, caloric e electric), in li tot
universe solmen li radies de catode have un plu grand rapiditá, i.e.
100 000 km/sec ye tension de 30 000 voltes.  E.P.

// XXX NOTE -- Ci esset ti separator: -----

// Reclame? {{{2
=== Reclame?

// XXX NOTE -- li marca original de págine -24- esset in li sequent
// paragraf:

… Null progress posse devenir populari sin reclame. Presc nequande un
progress esset salutat con joy e acceptat con favore quande it aparit.
On vell opiner, que nov inventiones es fat, pro que on sentit un
antiqui statu quam ínsuportabil, ínsuficent. Tre fallit! In li cap del
inventor li innovation nasce -- ma li publica curtmen refusa it; it
recomanda li ancian statu quam li plu bon, it ne ama li progress. Ci
li reclame deve comensat, it deve educar li publica e per lent labor
far acustomar it al progress. Solmen tande, pos decennies, li homes ne
comprende, qualmen ili posset perdurar jamá sin ti innovation ...

Ex «Handbuch der Reklame» (Manuale del reclame) de Johann Frank.
Tagblatt-Bibliothek Nr 600/604a Steyermühl-Verlag, Wien.

_E. Moess._

// XXX NOTE -- Ci esset ti separator: -----

// Subventiones al Occidental-Union {{{2
=== Subventiones al Occidental-Union

Albert Haldin (Eskilstuna): 100 sved K. -- Jan Casse (Köbenhavn): 107
ö. S. -- General Director Gerald A. Moore (London): 33 pounds. --
Reg.-Rat Dr. Mell (Saalfeld-S.): 15 RM. -- R. Weber (Argenteuil): 15
frs. fr. -- Prof. Dr. E. Küppers (Freiburg i.B.): 10 ö. S. -- H.
Gaminger (Judenburg): 5 ö. S. -- Cap. Giovanni Zaccaro (Brindisi): 19
Lire.

Cordial mersí.

Occidental-Union + Central Oficie.

// XXX NOTE -- Ci esset ti separator: -----

// Avises {{{2
=== Avises

Por impedir interruptiones in li expedition del revúe, nor letores mey
payar immediatmen li abonnament por 1930 per postmandate o banknotes o
chec in lettre registrat (recomandat) al adresse: Cosmoglotta,
Postfach 10, Mauer bei Wien, o anc per chec postal in li landes:

Austria: Postsparkassen-Scheckkonto Nr. B-125.211, Sparkasse Mauer,
Konto 3137.

Germania: Postscheckkonto Köln 7831. Dr. August Peipers.

Francia: Chèques postaux Strasbourg 94.49, G. Bohin.

Svissia: Postchec-Conto II. 1969, Fred. Lagnel, Chapelle (Vaud).

Tchecoslovacia: 29.428 Praha, Milan Nedvídek, Tábor.

Li simplic abonnament annual por 1930 custa 0,5 Dollar = 3,5 ö. S. =
2,6 sv. fr. = 2,1 RM = 16 c. K.

Un abonnament de propaganda custa li duplic precie (1 Dollar), in
compensation de quel li administration misse tri exemplares del revúe.

Payamentes ulterior por subtener nor propaganda e ameliorar li revúe
va esser acceptat con grand mersí e publicat in Cosmoglotta sub
rubrica «Subventiones» con indication del plen nómine del donator si
li don es plu grand quam 0,5 Dollar e si un altri desir ne es
expresset.

Li tabelle de contenete de Cosmoglotta 1929 va esser juntet al sequent
numeró.   Administration.

// XXX NOTE -- Ci esset ti separator: -----

// XXX TODO -- Titular:

Eigentümer, Herausgeber u. Verleger: Occidental-Union, Sitz: Mauer b.
Wien. Verantwortl. Redakteur: Ing. Engelbert Pigal, Liesing bei Wien.
Druck: Milan Nedvídek, Tábor.

// Cosmoglotta A 087 (mar-apr 1933) {{{1
== Cosmoglotta A 087 (mar-apr 1933)

COSMOGLOTTA

Annu XII   Marte-April 1933    No. 2 (87)

A.Z. Ramstedt.

Depos ti annu de Cosmoglotta -- o plu precis, depos ti ci numeró -- Sr
Mag. phil. A.Z. Ramstedt exmanua se li redactoratu de nor central
revúe. It es caracteristic por ti hom que mem su demission esset
motivat in prim loco per cuida pri li regulari edition del revúe e
solmen in duesim loco per personal aferes. Noi ne posse supresser nor
admiration por su persistentie e devotion al poc remunerativ labor in
ti dur témpores, queles nullmen ha sparat su propri patria e li
inhabitantes de it.

Durant li du annus de su redactoratu Mag. Ramstedt ha elevat
Cosmoglotta a un alt nivelle e, sin dúbita, su bon conosset e
judiciosi articules pri interlinguistic questiones, scrit in un clar e
admirabil stil, ha mult contribuet  a iluminar li problemas e
principies del LI auxiliari e a stimular li sempre crescent interesse
pri li fundamental idés del naturalistic conception del LI.

Per su vast practic conossentie de vivent lingues, su scientic studies
e su long familiaritá con li interlinguistic movement, quam anc per su
calm e clar perception del punctus cardinal it es specialmen
qualificat luder un rol important sur li camp moventat del
interlinguistica.

// XXX NOTE -- li marca original de págine -17- esset in li sequent
// paragraf:

Noi es cert que omni letores de ti revúe unia se con nos por presentar
a Sr Ramstedt nor calid mersías pro su desinteressat e valorós labor
por occidental e li organ central del occidental movement, e por
desirar a il bon success in li professional
activitás, a queles il va nu esser fortiat devoer su tot témpore. Mey
it anc esser permisset a nos expresser li esperantie, que il va
bentost trovar li ocasion revenir a su car Cosmoglotta.

_Por li redaction + B. Blomé_

// XXX NOTE -- Ci esset ti separator: ---

// Occidental es ínevitabil {{{2
=== Occidental es ínevitabil

_De S.W. Beer, del Universitás de London e Cambridge._

On di que li Angleso es sempre practic. Nu, yo es un Angleso, e yo do
adhere a Occidental pro un tre practic rason; to es que Occidental es
ínevitabil.

Nor civilisation es un unitá. Li Europan lingues es membres del sam
familie. Lor separat existentie es un mite. Por scientie, musica, c.,
li tot Europa usa li sam vocabularium. Li lingues difere solmen in li
grammatica, li pronunciation e li plu comun vocabules. Omnicos directe
al desirabilitá de un nov lingua franca: on refusa continuar payar
custosi traductores. It solmen va esser necessi far uniform
grammatica, pronunciation e plu comun paroles. Ma quande lingues
coalesce, li grammatica del resultant lingue es plu simplic e regulari
quam ti del coalescent lingues. Li nov lingua franca va esser plu
simplic e regulari quam li existent Europan lingues. It va esser tam
simplic quam Occidental: in fact, it va ''esser''  Occidental. A un
Angleso it va semblar un simplificat Anglés, quam un skeptic Cambridge
amico dit me que Occidental es.

On conosse un ver civilisation per su linguistic unitá. Ad-avan, do,
al universal auxiliari lingue!

// XXX NOTE -- Ci esset ti separator: ---

// XXX FIXME -- Titular:

Ante poc annus un autor parlat con un famós professor de fisica pri
ocultistic fenomenes. Startante del conception que on ne deve
controlar observationes e factes per teories, ma invers, e que chascun
teorie omni die deve resister a repetit nov provas, il urget li
professor ocupar se pri ti problemas. Li response esset que to velle
esser por il tro dangerós, nam quande il vell devenir convictet pri li
realitá de ti fenomenes, il vell perdir su reputation che li colegos
expertes.

// XXX NOTE -- Ci esset li marca original de págine -18-

// Nov sufixes in Esperanto {{{2
=== Nov sufixes in Esperanto

Pos li aparition de Ido li espistes ha provat justificar li derivativ
parol-structura de Esperanto. De Saussure ha defendet Espo e volet
pruvar, que li national lingues sta constructet ínlogicmen. Ma
Occidental ha demonstrat, que in veritá ili es tre ingeniosi. Ergo du
divers resultates sta contra unaltru. Támen, mem Espo in cert casus es
in desfacilitás con su sistema. Sovent in Espo on ne posse indicar
precismen, ex quel parol-categorie proveni un derivation, proque li
pur vocalic desinenties es supresset, p.ex. kronejo (sala del corones
o del conoration?), varmigi (igi varma o igi varmo?). Occidental sempre have
plurilitteral desinenties finient ye un consonant: -ion, -ment, -al,
-in, -ic, -ori, -ari, -ore e li apartenent derivationes: -ional,
-mental, -inar, -icism, -oria, -arisar, -orosi (conventional,
fundamental, vaccinar, catolicism, auditoria, popularisar,
centralisar, vigorosi). Nu on posse leer in li libre "Li lingual
normalisation international in li tecnica", de Dr Wüster, li sequent
reformatori proposition con li nov sufixes -on, -al, -ir: sanona
(concernent li sanitá = sanitari), audona (concernent li audie =
audial), protektonisto (= protectionist), unudirektona (=
unidirectional), jarcentona (= centenari), acidonigi (= acidificar),
homaligi (= humanisar), imperialigi (= imperialisar), racialigi (=
rationalisar), reformiro (= reformation, "reformo" es li finit fact!),
formirigi (= far formar), florira (concernent li floreantie =
floreantial!). Naturalmen Occidental ne besona tal bombastic expressiones.
Remarcabil es li adaptation al international sufixes (-ion, -ena,
-al). Espo incorpora se manicos ex li modern sistemas, ma it ne fa
comprender li etimologic coherentie. Wüster vole evitar demísufixes
(sanitara, lokalizi, reformacio, impresionisto) o oficialisar e
regular les per tal intersufixes. Esque in tal maniere (substantives
"on", adjectives "al", verbes "ir") to ha successat? It mey monstrar,
que Occidental es sur li recv via.   W. Karch, Leipzig.

// XXX NOTE -- Ci esset ti separator: ---

// XXX FIXME -- Titular:

Coidealistes de Görlitz e circumité, del Pruss e Saxon Supri Lusatia,
ples relater con Ernst Böhmer, Görlitz, Landeskronstr. 30. Un
postcarte sufice.

// XXX NOTE -- Ci esset li marca original de págine -19-

// Propaganda {{{2
=== Propaganda

_De K. Janotta, Wien._

Nu ha venit li témpor in quel noi posse comensar un vivaci propaganda
por Occidental, nam noi nu es capaci e pret executer li necessi
labores. Ma es necessi que omni occidentalistes colabora chascun secun
su capacitá e possibilitá.

// XXX NOTE -- li marca original de págine -20- esset in listun 3:

// XXX NOTE -- li marca original de págine -21- esset in listun 8:

// XXX NOTE -- li marca original de págine -22- esset in listun 11: 

1. Personal propaganda. Li max simplic metode es distribuer
   propagatori printates. Maxim avantageosi es provar recrutar por
   Occidental solmen persones queles es capabil comprender li idé
   interlinguistic e capaci aprender lingues.

Li coidealistes queles ne vole self interrelatar con li persones
recrutand posse misser al landal Central-Oficie li respectiv adresses.
Sovente on have plu facil success pri conossetes, si ili recive
printates de un altri expeditor.

2. Propaganda in jurnales. Qui vole far propaganda plu expeditiv e plu
   eficaci posse usar du vias. Li un via es li publication de
   articules pri occidental in jurnales e revúes; ti persones queles
   ne es tre habil in scrir self tal articules, posse tornar se anc al
   Central Oficie o al centres del national organisationes del
   Occidental-Union; por raport in li Cronica de "Cosmoglotta" it es
   sempre necessi misser al Redaction adminim un exemplar del numeró
   del jurnale in quel li articul ha aparit.

3. Discurses. Li altri via es li arangeament de discurses pri li idé
   de un lingue international in societés, scoles, sanatorias etc. Si
   on self ne posse far tal discurses, on adminim posse arangear les.
   Li adresses de referentes es recivibil del landal organisationes. A
   ti qui vole self far discurses, noi posse dar li sequent
   indicationes. It es absolut necessi demonstrar li lingue self; to
   posse esser fat per crete sur un nigri tabul o per projection de
   diapositives per un diascop o per projection de scrit e printat
   textus per un episcop o per grand afiches o per li distribution
   gratuit de preparat textus al auditores ante li discurs. It es bon
   si on posse lassar anunciar un curs de Occidental, quel deve
   comensar strax pos li discurs. It es preferibil que li presidente
   fa ti anuncia e ne li referente.

Pos li discurs mey evenir un líber discussion. On posse iniciar plu
facilmen ti discussion per que li presidente permisse anc li scrit
presentation de questiones.

4. Expositiones. Un bon medie de propaganda es li arangeament de
expositiones in vitrines de librerías, de societés etc. o in public
salas, forsan junt con discurses. On posse exposir ta libres,
brochuras, revúes, epistules, postcartes, propaganda-marcas, excerptes
ex jurnales, fotogrammas, afiches con textus etc. Por tal expositiones
migrant it es bon usar li international formates por ne perdir
non-usat plazze in li impaccament.

5. Cursus. Por ne perdir in van li labore fat, it es absolut necessi
arangear cursus tam mult quam possibil. Cursus posse esser fat ne
solmen oralmen in scoles e locales de societés, ma anc printat in
jurnales e revúes.

6. Radiodifusion. Ma li max eficaci medie de propaganda es li radio.
Do on mey efortiar utilisar li radio por li propaganda de Occidental.
Li textus necessi va esser liverat del Central Oficie.
7. Fonoilm. Un musica de futur es naturalmen li usa del fonofilm por
li propaganda de Occidental. Ma forsan just ti medie de international
comunication va esser ti quel quam unesim va introducter Occidental
pro maxim urgentie; nam it besona un lingue vermen international,
comprensibil sin long prestudie de omni erudites, ma ne un "lingvo
internacia kasha kun memstaraj eroj artefaritaj" (un lingue in-
ternational secret con autonom elementes artificial), quam scrit nos
un nov occidental-adherente, antey fervent esperanlist conosset.

8. Propaganda-textus. Por ti coidealistes queles self vole composir
propaganda-textus, noi da li consilie, que in ti textus on mey usar
secun possibilitá solmen tal paroles queles es comprensibil e a
franceses e a angleses e a germanes per li extran (doct) paroles de
lor lingues. Ergo on mey evitar paroles purmen latin-antiqui o grec o
hispan o altri tales ne (sat) international, quam p. ex.: do, nam,
pri, che, ye, presc, por, li, anc, chascun, nu, secun, misser, desde,
hay, vez, qualmen; ci on mey preferer (si li sense permisse): ergo,
de, a, quasi, in, per, in present, conform a, expedir, depos, existe,
per quel maniere. It ne es li culpa de Occidental que por 10% del
notiones ne existe international formes. Fortunosmen ti paroles es tre
rar. Solmen fensores de capilles e mesquin querellantes ci vide
obstacules ínsuperabil por li natural introduction de un L.I. Ver
amicos del idé va vider in prim li grand trates e ili va acconosser
que li solution es possibil solmen sur li fundament del existent
international paroles i.e. li fundament de Occidental.

9. Transition de adherentes de altri sistemas interlinguistic a
Occidental. Plu e plu augmenta Se li casus, que partisanes de altri
sistemas interlinguistic comunica a occidentalistes que ili es in
grand dúbitas esque ili deve transir oficialmen a Occidental o restar
in lor circules interlinguistic. Nor opinion es to que it es plu
avantageosi, si tal coidealistes resta in lor circules, evoca ta
discussiones pri Occidental, demanda discurses e labora sin fanatisme
ma persistentmen in omni maniere por efecter un decision del tot
gruppe (club etc.) por Occidental.

Ma noi anc vole constatar que noi mem ne desira e consilia que tot
organisationes, adherent til nu a un altri sistema de lingue
international, mey abandonar lor mundal organisation. Ili mey, si ili
vole acter in alquel maniere por Occidental, iniciar favorabil
decisiones por Occidental.

10. Resolutiones por Occidental. Ma noi deve accentuar que in general
tal resolutiones por un lingue international have poc valore. Li
experientie pri Esperanto monstra nos, que omni oficialisationes e
simil public honores per autorités have null valore e mem es nociv por
li movement, si ili ne es precedet o accompaniat per li realitá. Un
oficialisation sin li solid base del majorité es plu mult un fiasco
quam un success.

11. Propaganda per e por "Cosmoglotta". Un del max bon medies de
propaganda es li presentation de nor revúe oficial. Naturalmen it vell
esser avantageosi, si noi posset amplificar su contenete. To va esser
possibil solmen per li augmentation del númer de abonnates e
subventionatores.

Chascun occidentalist posse facilmen auxiliar nos per que il recruta
abonnates e subventionatores por "Cosmoglotta". Si il ne posse o ne
vole far to de person a person, il posse misser
nos li adresses de eventual interessates con precis indicationes pro
quel cause il opine chascun person quam probabil interessat. Poy noi
va tractar singul interessate in individual maniere.

Noi peti tornar atention a bon situat persones queles auxilia e favora
altri idealistic movementes.

Noi concede a omni hom quel auxilia nos per li aquisition de nov
abonnates, un gratuit abonnament por du abonnates nov ganat de il.

Ma til que tal action va dar su efectes, noi quam til nu va reciver
plu mult manuscrites por nor revúe quam noi posse inserter. Pro to
mult coidealistes forsan ja colerat nos. Ma it existe un medie que
chascun scritor posse vider insertet su manuscrite in "Cosmoglotta",
i.e. li procuration de un suficent subsidie por li surpluscustas del
printation, expedition etc.  Continuation va sequer.

// XXX NOTE -- Ci esset ti separator: ---

// Autoritás e progress {{{2
=== Autoritás e progress

Quande in Il annu 1752 li Reyal Societé in Anglia introductet li
Calendare gregorian, quelc membres del Societé esset persecutet in li
strades de London per li excitat populache proque ili, secun li nov
cronologie, ha raubat les 11 dies de lor vive.

In annu 1306 li rey Eduard I ha prohibit in Anglia brular carbon pro
cause del fum e li mal odore.

Circum li annu 1600 in Germania un machine por texter ha esset
inventet, li tal-nominat "Mühlstuhl", quel havet un machinerie de
rotes e impulsion mecanical e quel significat un essential del anteyan
metode de fabrication. Proque li laboreros protestat contra li
concurrentie, li imperial oficie in li annus 1681, 1685 e 1719 ha edit
sempre nov decretes prohibient li aplication del machine textori in li
german industries. Ma on ha denove admisset ti machines unesim in
Saxonia e mem subventionat les per premies, quande on devet sanar li
grav vúlneres causat del sett-annual guerre. Do durant plu quam un
secul e demí li public autoritás ha oposit se contra li usu de un tal
important invention.

// XXX NOTE -- Ci esset li marca original de págine -23-

Prof. H. Pašma

Presidente del Occidental-Academie.

(Linos de Rie. Berger, prof.)

Quande Lavoisier analysat li aer in su componentes e decovrit que it
consiste principalmen del du gases oxigen e nitrogen, ergo que it ne
es element, ti decovrition evocat un tumultu de indignation. Li
chemico Baumé, inventor del aerometre e membre del Academie del
Scienties, fulminante protestat: "Li elementes del córpores es
agnoscet e constatat del fisicos de omni secules e de omni nationes.
It ne es admissibil que li elementes aconosset desde 2000 annus hodie
vell esser inregistrat in li categorie del composit substanties. On
posse tranquilmen regardar quam íncert li processu decomposir aer e
aqua in partes elementari; ma negar li existentie de foy e terre quam
elementes es un totalmen absurd babillada, por ne usar plu fort
paroles. Li qualitás atribuet al elementes es congruent con li chimic
e fisic conossenties aquisitet til hodie; ti saventies ha servit quam
bases de un amasse de decovritiones e teories, li un plu brilliant
quam li altri, on vell deprivar ti doctrinas de omni autenticitá, si
on ne plu vell considerar foy, aqua e terre quam elementes
fundamental".

// XXX NOTE -- Ci esset li marca original de págine -24-

Dr. Jur. A. Peipers

Secretario del German Occidental-federation.

Quande un die on ha distinctmen observat li cadida de un meteor, quel
on videt lucer, audit li detonation, trovat it ancor tot ardent e
transmisset li meteor al academie por examination, li famós Lavoisier
scrit un tre doct raport al academie, in quel il pruvat li
ínpossibilitá de petres cadent del ciel.

Presc omni contemporanes acceptat con imens rision li observationes
del grand fisico Galvani pri li gambes de ran, e in persequentie de
quo il decovrit li electric currente, nominat secun il currente
galvanic. Il scrit pri to in 1792: "Yo es ataccat de du divers
parties, del sapientes e del stupides. Por ambi yo es object de moca,
e on nomina me li dans-mastre del ranes. Támen yo save que yo ha
decovrit un nov fortie natural."

Philippe Lebon, inventor de ilumination per gas (1797) ne ha successat
convicter li munde que un lampe posse arder anc sin meche. Solmen 14
annus post su morte, quel evenit 1804, on ha introductet su invention
in Paris, durant que Birmingham ja havet gas-ilumination in 1805.

_Trad. A. Deminger._

// XXX NOTE -- Ci esset li marca original de págine -25-

// Paternoster {{{2
=== Paternoster

Por facilisar un comparation instructiv inter li diferent projectes de
L.I. —-- li latin ja ha anc esset proposit quam LI — noi printa ci
infra divers' traductiones de un tre conosset textu, quel sovent ha
esset usat por comparativ scopes e quel have li avantage esser
diffuset tra li tot munde.

// XXX TODO -- Marcar:

LATIN. Pater noster, qui es in caelis. Sanctificetur nomen tuum,
adveniat regnum tuum. Fiat voluntas tua, sicut in caelis, et in terra.
Panem nostrum quotidianum da nobis hodie. Et dimitte nobis debita
nostra sicut et nos dimittimus debitoribus nostris. Et non induce nos
in tentationem, sed libera nos a malo.

VOLAPUK. O Fat Obas, kel binol in süls, paisaludomöz nem ola. Kömomöd
monargän Ola. Jenomöz vil olik, äs in siil, i su tal. Bodi obsik
vädeliki givolös obes adelo. E pardolös obes debis obsik, äs id obs
aipardobs debeles obas. E no obis nindukolös in tentadi, sod
aidalivolös obis de bad.

ESPERANTO. Patro nia, kiu estas en la chielo, sankta estu via nomo,
venu regeco via, estu volo via, tiel en la chielo, tiel ankau sur la
tero. Panon nian chiutagan donu al ni hodiau, kaj pardonu al ni
shuldojn niajn, kiel ni ankau pardonas al niaj Shuldantoj, kaj ne
konduku nin en la tenton, sed liberigu nin de la malbono.

IDO. Patro nia, qua esas en la cielo, tua nomo santigesez, tua regno
advenez, tua volo facesez quale en la cielo, tale anke sur la tero.
Donez a ni cadie l'omnidiala pano, e pardonez a ni nia ofensi, quale
anke ni pardonas a nia ofensantiy e ne duktez ni aden la tento, ma
liberigez ni del malajo.

IDIOM NEUTRAL. Nostr patr kel es in sieli. Ke Votr nom es sanktifiked,
ke votr regnia veni. ke votr volu es fasied, kuale in siel, tale et su
ter. Dona sidiurne a noi nostr pan omnidiurnik, e pardona a noi nostr
debti, kuale et noi pardon a nostr debtatori, e no induka noi in
tentasion, ma librifika noi da it mal.

// XXX NOTE -- Ci esset li marca original de págine -26-

REFORM NEUTRAL. Nostr pair, qui es in cieli. Que votr nom es
sanctificat, que votr regnia veni. Que votr voluntat es facit quale in
ciel tale anque su terr. Dona nos hodie nostr pan quotidian, e pardona
nos nostr debti quale anque noi pardona nostr debenti, e non induca
nos in tentasion ma librifica nos da it mal.

LATINO SINE FLEXIONE. Patre nostro, qui es in celos, que tuo nomine fi
sanctificato. Que tuo regno adveni, que tua voluntate es facta sicut
in celo et in terra. Da hodie ad nos nostro pane quotidiano. Et
remitte ad nos nostros debitos, sicut et nos remitte ad nostros
debitores. Et non induce nos in tentatione, sed libera nos ab malo.

ROMANAL. Patro nostri, qui est en cieles, sanctificat estas nomine
tui, advenias regne tui, fias volite tui, sicut en ciele, et en terre.
Il pane nostri quotidiani das ad nos hodie, et dimittas nostri
debites, sicut et nus dimitta debitantos nostri, et ne nos inducas in
tentatione, sed liberas nos ex male.

NOVIAL. Patre nusen, kel es in li siele, vun nome mey bli fika santi,
vun regia mey adveni, vun volo mey bli fa kam in li siele tam anke sur
li tere, Dona a nus disidi li omnidiali pane, e pardona a nus nusen
ofensos kom anke nus pardona a nusen ofensantes, e non dukte nus en Ii
tento ma fika nus liberi fro Ii malum.

OCCIDENTAL. Patre nor, qui es in li cieles. Mey tui nómine esser
sanctificat, mey tui reyia venir. Mey tui vole esser fat qualmen in li
cieles talmen anc sur li terre. Da nos hodie nor pan omnidial, e
pardona nor debites, qualmen anc noi pardona nor debitores. E ne
inducte nos in tentation, ma libera nos de lu mal.

// XXX TODO -- Titular:

Quande Franklin comunicat al Reyal Societé in London su experienties
pri li capabilitá de un mast ferrin a derivar li electricitá ex li
atmosphere, li sol response ha esset un eruption de serenitá, e li
erudit societé bruscmen declinat far printar li discurse pri li
parafúlmine.

// XXX NOTE -- Ci esset li marca original de págine -27-

// Li Banquette {{{2
=== Li Banquette

Un mann arangeat un grand banquette e invitat mult homes. E quande li
hor del banquette esset proxim, il inviat su domestico por dir al
invitates: "Ples venir, nam omnicos es nu parat."

Ma omnes comensat excusar se.

Li unesim dit ad il: "Yo ha comprat un possession e yo deve departer
por inspecter it. Yo peti te, ples acceptar mi excusa."

E un altri dit: "Yo ha comprat quin pares de boves e yo deve vader por
provar les. Yo peti te, ples acceptar mi excusa."

E un altri dit: "Yo ha just maritat e pro to yo ne posse venir nu."

E li domestico retornat e racontat to a su dómino. Tande li dómino
colerat e dit a su domestico:

"Vade for in li strades e stradettes del cité e aporta a ci li povres
e li stropiates e li claudicantes e li ciecos."

E li domestico dit: "Dómino, it es ja fat, quam tu ha imperat, e ancor
es líber plazzes."

Tande li dómino dit al domestico: "Vade for in li vias e hagas e
insiste que ili veni a ci, porque mi dom mey esser plenat. Nam yo di
vos, que nequi de ti mannes, queles esset invitat, va gustar de mi
banquette."

_Ex un old libre trad. A. Z. R._

// XXX NOTE -- Ci esset ti separator: ---

// Quo di li nationes pri li fémina? {{{2
=== Quo di li nationes pri li fémina?

In Francia on di: Li fémina, li vent e li fortune changea constant.

In Hispania on di: Un fémina deve vader solmen tri vezes ex su hem:
quande ella es confirmat, maritat e sepultet.

In Italia on di: Si on vole grives e chagrines in su vive, on deve
procurar se o un marita o un nave.

In Scotland on di: It es tragic por un fémina ne haver un lingue, ma
it es felici por li mann, con quel ella es maritat.

// XXX NOTE -- Ci esset li marca original de págine -28-

// Li mediocri hom {{{2
=== Li mediocri hom

De Ernest Hello.

Li absolutmen caracteristic trate del mediocri hom es su deferentie al
public opinion. Il nequande parla, il sempre repeti; il judica un hom
secun su etá, su profession, su success, su richess. Il have li max
grand respect por tis qui es conosset, por tis qui ha mult printat. Il
vell cortesar su max cruel ínamico, si ti ínamico vell devenir famós;
ma il ne vell cuidar mult pri su max bon amico, si nequi vell laudar
ti-ci. Il ne posse comprender que un hom ancor ínconosset, apu quel on
vive, pri quel on ne cuida, posse esser un geniós hom. Li mediocri hom
posse haver estima por li virtuós homes e por li talentós homes, ma il
have horrore e time del santes e del geniós homes. Il opine que ili
exagera.

_Trad. L.M.G._

// XXX NOTE -- Ci esset ti separator: ---

// Cronica {{{2
=== Cronica

HISPANIA. Pos har studiat li actual situation del LI e li diferent
sistemas proposit, pluri esperantistes de Hispania decidet adherer al
maxim modern solution, Occidental, e ha fundat li Hispan Association
por Occidental, Presidente: Sr Carlos Varela, Calle de Perelada Nr 5,
Figueras (Gerona), Hispania; Secretario: Sr Alberto Cabreiros
Curieses, Paseo de Taladriz Nr 4, Valladolid. Li comité de action ha
ja comensat li propaganda. Un long articul pri Occidental, publicat in
un jurnale de Valladolid, esset reproductet spontanimen de altri grand
diales de Hispania, quo monstra li interesse del Hispanos por nor
movement. Li editoría del Sviss Association por Occidental auxiliat li
nov hispan coidealistes per editer un curs de Occidental in hispan e mult
documentes por li propaganda. It es con grand plesur que noi save que
nor movement nu have un centre in Iberia.

FRANCIA. Articules de Ing. Thibault ha aparit in L'Ouest (Angers) e
L'Eveil des Peuples (Paris) ; de Sr Carbonnier in L'Etoile
Sténographique (Lille). Un anuncia ha esset insertet in li revúe de
sexual reforma "La Grande Réforme". Quelc lineas por Occidental ha aparit in
li januar Bulletin del Departement Marne del Sindicate National del
Instructeros.

// XXX NOTE -- li marca original de págine -29- esset in li sequent
// paragraf:

HELVETIA ha aparit con li nr 11/12 1932. Su índefatigabil redactor,
Prof. Ric. Berger, continua publicar interessant documentes pri
interlinguistic questiones. Ex li nro mentionat noi cita Li principie
de monosemie in li LI, Li situation del LI natural in 1908, Li exact
situation de Esperanto. Adplu ilustrationes e págines scientic.

L'OPINIO, Barcelona li 21.1.33, un grand jurnale catalan, contene un
long articul de sr Carles Varela, president del nov Hispan Association
por Occidental, pri li question de Ll. Li autor directe li atention
del publica e autoritás a occidental e li grand avantages atingibil
per labor por ti interlingue.

INFORMATIV FOLIETTES por li membres es distribuet del landal
organisationes in Svedia e Germania. In Svedia li informative apparit
du vezes durant 1932 con raportes pri li movement in Svedia e
extrania. In Germania li "German Occidentalist" da depos li current
annu simil informationes al membres del German Occidental-Federation e
aporta in ultra textus in occ. por letura. Li ultim numeró (2) contene
anc un necrolog pri sr Kurt Wallon, quel post 41 annus de labore por
espo transit a occ. in 1930 pos studie del libre pri novial de prof.
Jespersen!

THE INTERLANGUAGE "OCCIDENTAL" NEWS es li nómine de un propaganda
foliette editet del IAGB (Interlanguage Association of Great Britain).
Til nu tri numerós ha aparit con textus in angles e Occidental,
comparationes con Esperanto, etc. Li abonnament annual es 6 pence.

Un númere de grand anglesi e scott jurnales, quam SUNDAY REFEREE,
OXFORD MAGAZINE, THE OBSERVER, LANCASHIRE DAILY POST, SCOTTISH
EDUCATIONAL JOURNAL, BRISTOL EVENING POST, ha publicat, depos nov. del
annu passat, noticies pri occ.

In li jus aparit brochurette "LO BELA KOM PRINCIPO LINGUALA" sr
Quarfood, president del Ido-Academie, tracta li question de bellitá
lingual. Secun il ti bellitá depende ne del sones e del form exterior
del lingue ma del "signification e su associat idés". Il self e altri
erudites ha in comensa esset chocat de Ido; altri erudites ne ha
regardat li exterior aspecte del lingue in lor admiration del
"simpleso, facileso ed exakteso di Ido" e lor interesse por li idé del
mundelingue. "On do agez tre cirkonspekte," continua li autor, "pri la
egardo di naturaleso o beleso ye l'unesma vido." To on deve far "pro
que li judicie del homes depende anc del custom!" Tre bon! Ma qualmen
nu soluer li problema inspirar li grand masse del homes per un
entusiasme necessi por persuader les victer su aversion primari? Pro
quo, do, imposar al homanité ti "choc" del "Idigita" paroles in loco
de usar li acustomat formes sin complicationes, quam in occidental? To
sembla esser li ver consequentie de ti discussion pm. lingual bellitá
e custom por omnes ne talmen "Idigita" que ili trova omnicos exter
Ido, do anc li international paroles in occidental; "kruda soni e
formi".

// XXX FIXME -- "M astropaolo":

SCHOLA ET VITA, nov.—dec. 1932, contene inter altricos: Linguistica et
interlinguistica moderno, de G. Piccoli; Modern o antiquat, de E. de
Wahl; De derivatione et de grammatica, responses de N.  M astropaolo.

// XXX NOTE -- Ci esset li marca original de págine -30-

ESPERANTO, dec. 1932, publica li statutes del projectet Universala
Federacio Esperantista (U.F.A.), un federation del national societés
intentet quam substitution al Universala Esperanto Asocio (U.E.A.). Li
discussion pri ti organisatori questiones e li "plebescite" es nu tre
vivaci in esperantistic circules, e quelc ductores, quam Dr Privat,
time un ruptura del movement.

FRANCIA. Con dolore noi es informat del subit morte de nor coidealist
Dr Medico Thouvenin, quel evenit li 20 Januar in Saint Dié. Il esset
idist e adheret a Occidental del fundation del O.S.F.  Amico e
benefator de omni povres e suffrentes, su morte es un grand perde por
su cité. Mey il reposar in pace.

ASSOCIATION PROLETARI INTERLINGUISTIC (A.P.I.) es li nov nómine del
A.P. Occidentalistic. Li scope del societé es gruppar li
occidentalistes del laborant classe e de tendentie strictmen proletari
(socialistes, comunistes, anarchistes) por propaganda in jurnales de
laboreros e por organisation de correspondentie per Occidental. Pro que li
secretario til nu G. Bohin es impedit laborar activmen, licomité ha
nominat quam international secretario: Sr G. Poujet, in Heutregiville
par Warmeriville, Marne, Francia e quam vice-secretario Sr Karl
Krogstad, Bersvendveiten 16, Trondheim, Norvegia.  Omni interessates
es petit corresponder con li secretario.

SOCIETÉ OCCIDENTAL DE STOCKHOLM havet li 26m januar su unesim reunion
in 1933. Li societé obligat se cuidar li aferes de Cosmoglotta anc
durant 1933. Inter li punctus del programma on observat un discurs de
ing. A. Lindström pri li pronomines e particules in occidental. Li
orator emfasat que ti paroles deve esser seriosmen egardat del
novicies, e por li instruction il hat fat un detalliat liste contenent
ti paroles. Durant li proxim mensus li societé va arangear un
studiecircul in occidental in colaboration con li National Templar
Órden.

OCCIDENTAL IN Ll RADIO. Proque li Sved Radio-Servicie ha resoluet
arrangear pluri discurses pri li question de LI, durant li témpor 15m
febr.—15m marte, Dr B. Blome va far un discurs pri occidental li 3m
marte, clocca 6,55 -- 7,15. Post li clarificant discurses un general
discussion va evenir in fine de marte, in quel va participar
representantes de esperanto, ido, novial, anglic e occidental, quel
ultim va esser representat per doc. dr C. W. von Sydow. Undelongore:
Stockholm 435 m, Motala 1354 m.

NOV REPRESENTANTES NATIONAL. Post li printation del covrimentes de ti
annu noi peti nor letores notar li sequent nov informatores :

HISPANIA: Hispan por Occidental, Paseo de Taladriz Nr 4, VALLADOLID.

USSR: Dr A. Babadagly, Zolotovorotska N. 6/30, KIEV.

// XXX NOTE -- Ci esset ti separator: ---

// XXX TODO -- Marcar:

Esque vu ha ja payat vor abonnament?

// XXX NOTE -- Ci esset li marca original de págine -31-

// XXX TODO -- Titular:

Li Ver Essentie de Schweiklberg o Balsam de Sant Luis (destillat de
Sant Luis).

Sol fabricant es li monastere benedictin Schweiklberg pr. Vilshofen a.
I). Bass-Bavaria, Germania.

Excellent remedie de familie por índispositiones, refrigidationes,
grippe, reuma, cap-dolores etc.

Ples prender guttes sur sucre e frottar fronte, tempies e dolorós
locos per li balsam. Calid té de tilie-flores es li bonissim cura de
transpiration.

Precie por un botelle M. 1.25, por membres solmen M. 1.05. Precie por
un dozen botelles solmen M. 10.—

Comendabil per Missionario Pater Pelegrinus Hoffmann, Schweiklberg bei
Vilshofen a.D. Nieder-Bayern (Maria-Hilfs-Missionsverein)
Postscheckkonto: München 1109.

// XXX NOTE -- Ci esset ti separator: ---

// XXX TODO -- Titular:

Occidental, die Weltsprache.

Einführung samt Lehrkursus, Lesestücken, Häufigkeitswörterverzeichnis.
Herausgegeben von E. Pigal durch die Hauptstelle der Occidental-Union
in Wien. 256 Seiten RM 4,90, in Leinen RM 7,20. Portozuschlag fÜr das
Ausland: RM ——,30.

Leitfaden der Weltsprache Occidental.

Lehrgang, Lesestiicke und ausführliches Wörterverzeichnis Occidental-Deutsch
von Karl Janotta. 80 Seiten. Mit Bildern. RM —,80.

Sämtliche Occidental-Biicher können durch die Haupstelle der
Occidental-Union, Ehamg. 40, WIEN XI (Postscheckk. Wien B-84868) oder
durch Deutschen Occidental-Bund, BERLIN-BERNAU, Siedlung (Postsch.
Berlin 696.76), bezogen werden.

Edvard Rydahls Boktryckeri, Stockholm

// XXX NOTE -- Ci esset li marca original de págine -32-
